import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://sigizikesga.kemkes.go.id/login_sisfo/")
    page.get_by_role("textbox", name="").fill("dssukaasih")
    page.get_by_role("textbox", name="").press("Tab")
    page.get_by_role("textbox", name="Tampilkan Password ").fill("sukaasih")
    page.get_by_role("textbox", name="Tampilkan Password ").press("Tab")
    page.get_by_role("checkbox").press("Tab")
    page.get_by_role("textbox", name="Masukan kata yang terlihat").fill("sepeda")
    page.get_by_role("button", name=" Login").click()
    page.get_by_role("link", name="Pelayanan Kesehatan").click()
    page.goto("https://sigizikesga.kemkes.go.id/ppgbm/index.php/index_ppgbm.html")
    page.get_by_role("link", name=" ENTRY ").click()
    page.get_by_role("link", name=" Anak Prasekolah ").click()
    page.get_by_role("link", name="Tambah Anak Prasekolah").click()
    page.get_by_placeholder("Anak ke").click()
    page.get_by_placeholder("Anak ke").fill("2")
    page.locator("#TL").click()
    page.get_by_role("cell", name="«").click()
    page.get_by_role("cell", name="April").click()
    page.get_by_role("cell", name="«").click()
    page.get_by_role("cell", name="2024").click()
    page.get_by_role("cell", name="«").click()
    page.get_by_text("2015").click()
    page.get_by_text("Jun").click()
    page.get_by_role("cell", name="29").click()
    page.get_by_role("radio", name="Perempuan").check()
    page.get_by_role("textbox", name="Nomor Kartu Keluarga").click()
    page.get_by_role("textbox", name="Nomor Kartu Keluarga").fill("3209890018890005")
    page.get_by_role("textbox", name="NIK", exact=True).click()
    page.get_by_role("textbox", name="NIK", exact=True).fill("3278098711890001")
    page.get_by_role("textbox", name="Nama", exact=True).click()
    page.get_by_role("textbox", name="Nama", exact=True).fill("madam risa")
    page.get_by_placeholder("dalam minggu").click()
    page.get_by_placeholder("dalam minggu").fill("39")
    page.get_by_placeholder("Contoh : 4.3").click()
    page.get_by_placeholder("Contoh : 4.3").fill("2.6")
    page.get_by_placeholder("Contoh : 70").click()
    page.get_by_placeholder("Contoh : 70").fill("35")
    page.get_by_placeholder("Contoh : 33").click()
    page.get_by_placeholder("Contoh : 33").fill("27")
    page.get_by_role("form").locator("div").filter(has_text="Buku KIA Bayi Kecil* Ya Tidak").get_by_label("Ya").check()
    page.get_by_role("form").locator("div").filter(has_text="IMD Ya Tidak").get_by_label("Tidak").check()
    page.get_by_role("form").locator("div").filter(has_text="IMD Ya Tidak").get_by_label("Ya").check()
    page.get_by_role("textbox", name="Nama Orangtua").click()
    page.get_by_role("textbox", name="Nama Orangtua").fill("ramayana")
    page.get_by_role("textbox", name="NIK Orangtua").click()
    page.get_by_role("textbox", name="NIK Orangtua").fill("3298098109980008")
    page.get_by_role("textbox", name="Nomor Telepon/HP Orangtua").click()
    page.get_by_role("textbox", name="Nomor Telepon/HP Orangtua").fill("085687261009")
    page.get_by_title("JAWA BARAT").click()
    page.get_by_role("treeitem", name="JAWA BARAT").click()
    page.get_by_title("KAB KAB TASIKMALAYA").click()
    page.get_by_role("treeitem", name="KAB KAB TASIKMALAYA").click()
    page.get_by_title("SINGAPARNA").click()
    page.get_by_role("treeitem", name="SINGAPARNA").click()
    page.get_by_title("TINEWATI").click()
    page.get_by_role("treeitem", name="TINEWATI").click()
    page.get_by_title("SUKAASIH").click()
    page.get_by_role("treeitem", name="SUKAASIH").click()
    page.get_by_title("-- Silahkan Pilih --").click()
    page.get_by_role("treeitem", name="CISEDA").click()
    page.get_by_role("textbox", name="Alamat Lengkap").click()
    page.get_by_role("textbox", name="Alamat Lengkap").fill("jl. ciseda no 113")
    page.get_by_role("textbox", name="RT", exact=True).click()
    page.get_by_role("textbox", name="RT", exact=True).fill("009")
    page.get_by_role("textbox", name="RW").click()
    page.get_by_role("textbox", name="RW").fill("002")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
