import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://ekohort.kemkes.go.id/administrator/login")
    page.get_by_role("textbox", name="Pilih Provinsi").click()
    page.get_by_role("option", name="JAWA BARAT").click()
    kab = page.get_by_role("textbox", name="Pilih Kabupaten").click()
    for i in range(10):
        print("waiting for kabupaten")
        page.wait_for_timeout(1000)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        page.wait_for_timeout(100)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        kab = page.get_by_role("option", name="KABUPATEN TASIKMALAYA")
        print(kab)
        if kab.is_visible():
            print("kabupaten visible")
            break
    page.get_by_role("option", name="KABUPATEN TASIKMALAYA").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").fill("phone_number")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("password_here")
    page.get_by_role("button", name="Secure login").click()
    page.get_by_role("link", name=" Pelayanan KIA ").click()
    page.get_by_role("link", name=" Pelayanan Anak").click()
    page.get_by_role("link", name="image rf_m_ibuhamil P. BAYI (").click()
    page.get_by_role("row", name="Status Anak : Bayi Gol Darah: Berat: 3400 Panjang: 51 Kondisi Lahir: HIDUP Dicatat Buku KIA: yes Resiko Klinis: Belum diketahui (0) Tgl Monitoring Terakhir: 2024-06-25 Tgl Follow Up : 2024-07-25 N BY BT EPPGBM", exact=True).get_by_role("button").nth(2).click()
    page.get_by_role("button", name=" Mulai Periksa").click()
    page.get_by_role("link", name=" Tambahkan Data Layanan").click()
    page.locator("a").filter(has_text="Select Cara Masuk").click()
    page.locator("#cara_masuk_chosen").get_by_text("Atas Permintaan Sendiri").click()
    page.get_by_role("textbox", name="Tanggal Pemeriksaan *").fill("2025-05-16")
    page.get_by_role("spinbutton", name="Kunjungan Ke-").click()
    page.get_by_role("spinbutton", name="Kunjungan Ke-").fill("2")
    page.locator("a").filter(has_text="Select Lokasi Screening").click()
    page.locator("#lokasi_chosen").get_by_text("Poskesdes").click()
    page.locator("#kode_lembaga_chosen a").click()
    page.locator("#kode_lembaga_chosen").get_by_text("PUSKESMAS CIPATUJAH").click()
    page.locator("a").filter(has_text="Select Kode Lembaga").click()
    page.locator("#status_lembaga_chosen").get_by_text("Pemerintah").click()
    page.locator("a").filter(has_text="Select Nakes").click()
    page.locator("#nakes_chosen").get_by_text("Dokter", exact=True).click()
    page.get_by_role("radio", name="Ya").check()
    page.get_by_role("list").filter(has_text=re.compile(r"^$")).first.click()
    page.locator("#diagnosis_chosen").get_by_text("Hipotermi").click()
    page.get_by_role("list").filter(has_text=re.compile(r"^$")).first.click()
    page.locator("#diagnosis_chosen a").click()
    page.locator("#diagnosis_chosen").get_by_role("list").filter(has_text=re.compile(r"^$")).click()
    page.locator("#diagnosis_chosen").get_by_text("Hipotermi").click()
    page.locator("#diagnosis_chosen").get_by_role("textbox").click()
    page.locator("#diagnosis_chosen").get_by_text("Pneumoni").click()
    page.get_by_role("list").filter(has_text=re.compile(r"^$")).click()
    page.locator("#klasifikasi_mtbm_chosen").get_by_text("KBBR &/ MP ASI").click()
    page.get_by_role("list").filter(has_text=re.compile(r"^KBBR &/ MP ASI$")).click()
    page.locator("#klasifikasi_mtbm_chosen").get_by_text("KPSB /IB").click()
    page.get_by_role("textbox", name="Keterangan Bayi Sakit").click()
    page.get_by_role("textbox", name="Keterangan Bayi Sakit").fill("bayinya sakit")
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_text("HIV", exact=True).first.click()
    page.get_by_role("textbox", name="Tanda Bahaya").click()
    page.locator("#batuk1").check()
    page.get_by_role("textbox", name="Sudah berapa lama").click()
    page.get_by_role("textbox", name="Sudah berapa lama").fill("3")
    page.locator("#sukar_bernafas1").check()
    page.locator("#hari_sukar_bernafas").click()
    page.locator("#hari_sukar_bernafas").fill("3")
    page.locator("#diare1").check()
    page.locator("#hari_diare").click()
    page.locator("#hari_diare").fill("2")
    page.locator("#demam1").check()
    page.locator("#hari_demam").click()
    page.locator("#hari_demam").fill("2")
    page.locator("#nyeri_perut2").check()
    page.locator("#nyeri_telinga2").check()
    page.locator("#telinga_penuh1").check()
    page.locator("#hari_telinga_penuh").click()
    page.locator("#hari_telinga_penuh").fill("1")
    page.locator("#cairan_telinga1").check()
    page.locator("#hari_cairan_telinga").click()
    page.locator("#hari_cairan_telinga").fill("1")
    page.locator("#masalah_asi2").check()
    page.locator("#pendarahan2").check()
    page.locator("#mual1").check()
    page.locator("#hari_mual").click()
    page.locator("#hari_mual").fill("1")
    page.locator("div:nth-child(13) > div > div > .col-md-12 > label").first.click()
    page.locator("#hari_muntah").click()
    page.locator("#hari_muntah").fill("1")
    page.locator("#nyeri_badan1").check()
    page.locator("#hari_nyeri_badan").click()
    page.locator("#hari_nyeri_badan").fill("2")
    page.locator("#ruam2").check()
    page.locator("#badan_dingin2").check()
    page.locator("#masalah_bab2").check()
    page.locator("#masalah_bak1").check()
    page.locator("#hari_masalah_bak").click()
    page.locator("#hari_masalah_bak").fill("1")
    page.locator("#anak_rewel2").check()
    page.locator("#lainnya2").check()
    page.locator("#ibu_test_hiv1").check()
    page.get_by_role("radio", name="Negatif").check()
    page.locator("#endemis_malaria1").check()
    page.locator("#endemis_malaria2").check()
    page.locator("#pergi_endemis_malaria1").check()
    page.locator("#obat_malaria1").check()
    page.locator("#muntah_darah1").check()
    page.locator("#muntah_terus1").check()
    page.locator("#campak1").check()
    page.get_by_role("spinbutton", name="BAK terakhir(hari)").click()
    page.get_by_role("spinbutton", name="BAK terakhir(hari)").fill("1")
    page.get_by_role("spinbutton", name="BAK terakhir", exact=True).click()
    page.get_by_role("spinbutton", name="BAK terakhir", exact=True).fill("2")
    page.locator("#bab_merah_hitam1").check()
    page.locator("#lokasi_nyeri_badan_chosen a").click()
    page.locator("#lokasi_nyeri_badan_chosen").get_by_text("Mata").click()
    page.locator("#keadaan_umum_chosen a").click()
    page.locator("#keadaan_umum_chosen").get_by_text("Tidak sadar").click()
    page.get_by_role("textbox", name="Frekuensi Nafas", exact=True).click()
    page.get_by_role("textbox", name="Frekuensi Nafas", exact=True).fill("40")
    page.get_by_role("spinbutton", name="Saturasi Oksigen").click()
    page.get_by_role("spinbutton", name="Saturasi Oksigen").fill("70")
    page.get_by_role("spinbutton", name="Suhu").click()
    page.get_by_role("spinbutton", name="Suhu").fill("36")
    page.locator("#nadi_chosen a").click()
    page.locator("#nadi_chosen").get_by_text("Lemah").click()
    page.get_by_role("textbox", name="Frekuensi Nadi", exact=True).click()
    page.get_by_role("textbox", name="Frekuensi Nadi", exact=True).fill("30")
    page.locator("#mata_chosen a").click()
    page.locator("#mata_chosen").get_by_text("Merah").click()
    page.locator("#mulut_chosen a").click()
    page.locator("#mulut_chosen").get_by_text("Bibir pucat").click()
    page.locator("#telinga_chosen a").click()
    page.locator("#telinga_chosen").get_by_text("Pembengkakan di belakang").click()
    page.locator("#kaku_duduk_chosen a").click()
    page.locator("#kaku_duduk_chosen").get_by_text("Tidak").click()
    page.locator("#dada_chosen a").click()
    page.locator("#dada_chosen").get_by_text("Akumulasi cairan").click()
    page.locator("#perut_chosen a").click()
    page.locator("#perut_chosen").get_by_text("Akumulasi cairan").click()
    page.locator("#kulit_chosen a").click()
    page.locator("#kulit_chosen").get_by_text("Ruam kemerahan").click()
    page.locator("#ekstremitas_chosen a").click()
    page.locator("#ekstremitas_chosen").get_by_text("Edema derajat +2").click()
    page.locator("#kuku_chosen a").click()
    page.locator("#kuku_chosen").get_by_text("Kuku Pucat").click()
    page.locator("#uji_tourniquet_chosen a").click()
    page.locator("#uji_tourniquet_chosen").get_by_text("Negatif").click()
    page.get_by_role("textbox", name="BB").click()
    page.get_by_role("textbox", name="BB").fill("2000")
    page.get_by_role("textbox", name="PB/TB").click()
    page.get_by_role("textbox", name="PB/TB").fill("20")
    page.get_by_role("spinbutton", name="Lingkar Kepala").click()
    page.get_by_role("spinbutton", name="Lingkar Kepala").fill("10")
    page.get_by_label("Status lingkar kepala").select_option("Normal")
    page.get_by_label("Status Gizi (BB/PB atau BB/TB)").select_option("Gizi Lebih")
    page.get_by_label("Status Gizi (PB/U atau TB/U)").select_option("Pendek")
    page.get_by_label("Status Gizi (BB/U)").select_option("Normal")
    page.get_by_label("Status Gizi (IMT/U)").select_option("Gizi baik")
    page.get_by_role("spinbutton", name="Lila").click()
    page.get_by_role("spinbutton", name="Lila").fill("10")
    page.get_by_label("Kategori LilA").select_option("Gizi Kurang")
    page.get_by_label("Kenaikan Berat Badan dari").select_option("Tidak naik")
    page.get_by_role("radio", name="Tes HIV Ya").check()
    page.get_by_label("Pemeriksaan Darah", exact=True).select_option("Leukosit")
    page.get_by_label("Hasil pemeriksaan darah", exact=True).select_option("non-reaktif")
    page.get_by_role("textbox", name="Hasil pemeriksaan darah(").click()
    page.get_by_role("textbox", name="Hasil pemeriksaan darah(").fill("4000")
    page.get_by_label("Lab Kecacingan").select_option("negatif")
    page.get_by_label("Pemeriksaan TB", exact=True).select_option("positif")
    page.get_by_role("textbox", name="Hasil pemeriksaan TB").click()
    page.get_by_role("textbox", name="Hasil pemeriksaan TB").fill("10")
    page.get_by_role("textbox", name="Hasil Pemeriksaan Lab Lainnya").click()
    page.get_by_role("textbox", name="Hasil Pemeriksaan Lab Lainnya").fill("periksa lab")
    page.get_by_role("textbox", name="Pemeriksaan Penunjang Lainnya", exact=True).click()
    page.get_by_role("textbox", name="Pemeriksaan Penunjang Lainnya", exact=True).fill("penunjang lab")
    page.get_by_role("textbox", name="Hasil Pemeriksaan Penunjang").click()
    page.get_by_role("textbox", name="Hasil Pemeriksaan Penunjang").fill("lainnya")
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("textbox", name="Masalah Batuk/Sukar Bernapas").click()
    page.get_by_role("textbox", name="Masalah Diare").click()
    page.get_by_role("textbox", name="Masalah Demam").click()
    page.get_by_role("textbox", name="Pemantauan Pertumbuhan dan").click()
    page.get_by_role("textbox", name="Masalah Anemia").click()
    page.get_by_role("textbox", name="Masalah Anemia").fill("masalah anemia")
    page.get_by_role("textbox", name="Masalah HIV").click()
    page.get_by_role("textbox", name="Masalah HIV").fill("masalah hiv")
    page.get_by_label("Hb 0").select_option("sudah")
    page.locator("#imunisasi_tgl_1").fill("2025-05-07")
    page.locator("#imunisasi_batch_1").click()
    page.locator("#imunisasi_batch_1").fill("1")
    page.get_by_label("BCG dan OPV").select_option("belum")
    page.locator("#imunisasi_tgl_2").fill("2025-05-08")
    page.locator("#imunisasi_batch_2").click()
    page.locator("#imunisasi_batch_2").fill("1")
    page.get_by_label("DPT HB Hib 1, OPV 1, RV 1, PCV").select_option("sudah")
    page.locator("#imunisasi_tgl_3").fill("2025-05-15")
    page.locator("#imunisasi_batch_3").click()
    page.locator("#imunisasi_batch_3").fill("2")
    page.get_by_label("DPT HB Hib 2, OPV 2, RV 2, PCV").select_option("sudah")
    page.locator("#imunisasi_tgl_4").fill("2025-05-07")
    page.locator("#imunisasi_batch_4").click()
    page.locator("#imunisasi_batch_4").fill("2")
    page.get_by_label("DPT HB Hib 3, OPV 3, RV").select_option("sudah")
    page.locator("#imunisasi_tgl_5").fill("2025-05-15")
    page.locator("#imunisasi_batch_5").click()
    page.locator("#imunisasi_batch_5").fill("1")
    page.get_by_role("radio", name="Pemberian Vitamin A Ya").check()
    page.get_by_role("textbox", name="Terakhir kali mendapat").fill("2025-05-16")
    page.get_by_role("spinbutton", name="Usia terakhir kali").click()
    page.get_by_role("spinbutton", name="Usia terakhir kali").fill("3")
    page.get_by_role("textbox", name="Dosis vitamin A").click()
    page.get_by_role("textbox", name="Dosis vitamin A").fill("1")
    page.locator("#sdidtk1").check()
    page.locator("a").filter(has_text="Select Sdi Tk Bbu").click()
    page.locator("#sdi_tk_bbu_chosen").get_by_text("K", exact=True).click()
    page.locator("a").filter(has_text="Select Sdi Tk Tbu").click()
    page.locator("#sdi_tk_tbu_chosen").get_by_text("SP").click()
    page.locator("a").filter(has_text="Select Sdi Tk Bbtb").click()
    page.locator("#sdi_tk_bbtb_chosen").get_by_text("Kurus", exact=True).click()
    page.locator("a").filter(has_text="Select Sdi Tk Lku").click()
    page.locator("#sdi_tk_lku_chosen").get_by_text("Microcephalus").click()
    page.locator("a").filter(has_text="Select Sdt Dtk Kpsp").click()
    page.locator("#sdt_dtk_kpsp_chosen").get_by_text("Sesuai").click()
    page.locator("a").filter(has_text="Select SDIDTK TDD").click()
    page.locator("#sdt_dtk_tdd_chosen").get_by_text("Ragu").click()
    page.locator("a").filter(has_text="Select SDIDTK TDL").click()
    page.locator("#sdt_dtk_tdl_chosen").get_by_text("Ragu").click()
    page.locator("a").filter(has_text="Select SDIDTK GPPH").click()
    page.locator("#sdt_dtk_gpph_chosen").get_by_text("Normal").click()
    page.locator("a").filter(has_text="Select SDIDTK M-CHAT").click()
    page.locator("#sdi_tk_mchat_chosen").get_by_text("Normal").click()
    page.locator("a").filter(has_text="Select SDIDTK KMPE").click()
    page.locator("#sdt_dtk_kampe_chosen").get_by_text("Normal").click()
    page.get_by_role("textbox", name="Diagnosa").click()
    page.get_by_role("textbox", name="Diagnosa").fill("diagnosa 1")
    page.get_by_role("textbox", name="Kode ICD").click()
    page.get_by_role("textbox", name="Kode ICD").fill("icd 10")
    page.get_by_role("textbox", name="Pemberian bantuan hidup dasar").click()
    page.get_by_role("textbox", name="Pemberian bantuan hidup dasar").fill("bantuan dasar")
    page.locator("#pembebasan_jalan_nafas1").check()
    page.locator("#pemberian_obat_cairan_chosen a").click()
    page.locator("#pemberian_obat_cairan_chosen").get_by_text("Obat Wheezing").click()
    page.locator("#jenis_obat_chosen a").click()
    page.locator("#jenis_obat_chosen").get_by_text("Cairan").click()
    page.locator("#metode_pemberian_chosen a").click()
    page.locator("#metode_pemberian_chosen").get_by_text("Injeksi").click()
    page.get_by_role("textbox", name="Dosis Pemberian Obat/Cairan").click()
    page.get_by_role("textbox", name="Dosis Pemberian Obat/Cairan").fill("10")
    page.locator("#pemberian_oksigen1").check()
    page.get_by_role("textbox", name="Metode", exact=True).click()
    page.get_by_role("textbox", name="Metode", exact=True).fill("oral")
    page.get_by_role("spinbutton", name="Dosis Pemberian O2").click()
    page.get_by_role("spinbutton", name="Dosis Pemberian O2").fill("1")
    page.locator("div:nth-child(7) > div > .col-md-12 > label").first.click()
    page.locator("#metode_pencegahan_gula_darah").click()
    page.locator("#metode_pencegahan_gula_darah").fill("turun")
    page.get_by_role("spinbutton", name="Dosis Pencegahan gula darah").click()
    page.get_by_role("spinbutton", name="Dosis Pencegahan gula darah").fill("1")
    page.locator("div:nth-child(3) > div:nth-child(10) > div > .col-md-12 > label").first.click()
    page.locator("#metode_pencegahan_suhu_tubuh_turun").click()
    page.locator("#metode_pencegahan_suhu_tubuh_turun").fill("metode gula")
    page.locator("#pemberian_imunisasi1").check()
    page.get_by_role("list").filter(has_text=re.compile(r"^$")).first.click()
    page.locator("#pencegahan_chosen").get_by_text("DPT2").click()
    page.get_by_role("textbox", name="Tanggal Pemberian").fill("2025-05-15")
    page.get_by_role("textbox", name="No Batch", exact=True).click()
    page.get_by_role("textbox", name="No Batch", exact=True).fill("1")
    page.get_by_role("textbox", name="Jenis makanan").click()
    page.get_by_role("textbox", name="Jenis makanan").fill("makanan sehat")
    page.get_by_role("textbox", name="Jumlah yang telah didapatkan").click()
    page.get_by_role("textbox", name="Jumlah yang telah didapatkan").fill("1")
    page.get_by_role("textbox", name="Jumlah yang saat ini diberikan").click()
    page.get_by_role("textbox", name="Jumlah yang saat ini diberikan").fill("2")
    page.get_by_role("textbox", name="Tatalaksana Lainnya").click()
    page.get_by_role("textbox", name="Tatalaksana Lainnya").fill("tatalaksana lain")
    page.get_by_label("Step 3").locator("div").filter(has_text="Konseling/KIE Pemberian KIE/").locator("label").nth(1).click()
    page.locator("#jenis_kie_chosen a").click()
    page.locator("#jenis_kie_chosen").get_by_text("Pengobatan infeksi local di").click()
    page.locator("div:nth-child(6) > .panel-container > .panel-content > div > .row > div > div > .col-md-12 > label").first.click()
    page.get_by_role("textbox", name="Alasan dirujuk").click()
    page.get_by_role("textbox", name="Alasan dirujuk").fill("sakit kepala")
    page.get_by_role("radio", name="RS").check()
    page.locator("#kab_kota_dituju_chosen a").click()
    page.locator("#kab_kota_dituju_chosen a").click()
    page.locator("#kab_kota_dituju_chosen a").click()
    page.locator("#kab_kota_dituju_chosen").get_by_role("textbox").fill("")
    page.get_by_role("textbox", name="Nama Faskes").click()
    page.get_by_role("textbox", name="Nama Faskes").fill("puskesmas")
    page.get_by_role("textbox", name="Keterangan lainnya").click()
    page.get_by_role("textbox", name="Keterangan lainnya").fill("keterangan kontrol")
    page.locator("#kunjungan_ulang1").check()
    page.get_by_role("textbox", name="Tanggal kontrol ulang").fill("2024-07-31")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
