import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://ekohort.kemkes.go.id/administrator/login")
    page.get_by_role("textbox", name="Pilih Provinsi").click()
    page.get_by_role("option", name="JAWA BARAT").click()
    kab = page.get_by_role("textbox", name="Pilih Kabupaten").click()
    while kab is None:
        print("waiting for kabupaten")
        page.wait_for_timeout(1000)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        page.wait_for_timeout(100)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        kab = page.get_by_role("option", name="KABUPATEN TASIKMALAYA")
    page.get_by_role("option", name="KABUPATEN TASIKMALAYA").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").fill("08")
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").fill("081224600500")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("123456")
    page.get_by_role("button", name="Secure login").click()
    page.get_by_role("link", name=" Pelayanan KIA ").click()
    page.get_by_role("link", name=" Pelayanan Anak").click()
    page.get_by_role("link", name="image rf_m_ibuhamil P. NEONATUS (62) ").click()
    page.get_by_role("cell", name="Tgl Monitoring Terakhir: 2024-09-28 Tgl Follow Up : 0000-00-00 N BY BT EPPGBM", exact=True).get_by_role("button").first.click()
    page.get_by_role("button", name=" Mulai Monitoring").click()
    page.get_by_role("link", name=" Tambahkan Layanan").click()
    page.locator("a").filter(has_text="Select Cara Masuk").click()
    page.locator("#cara_masuk_chosen").get_by_text("Dirujuk").click()
    page.locator("#id_prov_rujuk_chosen a").click()
    page.locator("#id_prov_rujuk_chosen").get_by_text("JAWA BARAT").click()
    page.locator("#id_kab_rujuk_chosen a").click()
    page.locator("#id_kab_rujuk_chosen").get_by_text("KABUPATEN TASIKMALAYA").click()
    page.locator("#nama_faskes_rujukan_chosen a").click()
    page.locator("#nama_faskes_rujukan_chosen").get_by_role("textbox").fill("")
    page.locator("#nama_faskes_rujukan_chosen").get_by_text("KLINIK UMMI MEDIKA").click()
    page.locator("a").filter(has_text="Select jenis Faskes").click()
    page.locator("#jenis_faskes_chosen").get_by_text("Praktek Bidan").click()
    page.get_by_role("textbox", name="Diagnosa Rujukan").click()
    page.get_by_role("textbox", name="Diagnosa Rujukan").fill("sakit kepala")
    page.get_by_role("textbox", name="Tatalaksana Rujukan").click()
    page.get_by_role("textbox", name="Tatalaksana Rujukan").fill("minum obat sakit")
    page.locator("a").filter(has_text="Bulan").click()
    page.get_by_role("listitem").filter(has_text="Bulan").click()
    page.locator("a").filter(has_text="Select Kunjungan K").click()
    page.locator("#kunjungan_chosen").get_by_text("KN 3").click()
    page.locator("a").filter(has_text="Select Lokasi Screening").click()
    page.locator("#lokasi_chosen").get_by_text("Puskesmas").click()
    page.locator("a").filter(has_text="PUSKESMAS TINEWATI").click()
    page.locator("#kode_lembaga_chosen").get_by_role("list").get_by_text("PUSKESMAS TINEWATI").click()
    page.locator("a").filter(has_text="Select Status Lembaga").click()
    page.locator("#status_lembaga_chosen").get_by_text("Swasta").click()
    page.locator("a").filter(has_text="Select Nakes").click()
    page.locator("#nakes_chosen").get_by_text("Bidan").click()
    page.get_by_role("menuitem", name="Next").click()
    page.locator("#a_shk_kunjungan").get_by_text("Ya").click()
    page.locator("a").filter(has_text="Sampel 1").click()
    page.locator("#sample_ke_chosen").get_by_text("Sampel 2").click()
    page.get_by_placeholder("Tanggal Pengambilan Sample").fill("2025-05-16")
    page.locator("a").filter(has_text="Tenaga Pengambilan Sampel").click()
    page.locator("#tenaga_pengambil_sampel_chosen").get_by_text("Bidan").click()
    page.locator("a").filter(has_text="Nama Pengambilan Sampel").click()
    page.locator("#nama_pengambil_sampel_chosen").get_by_text("RISKA ROSALINA").click()
    page.locator("a").filter(has_text="Pengambilan Sampel Darah").click()
    page.locator("#sample_darah_tumit_chosen").get_by_text("Vena").click()
    page.get_by_role("textbox", name="no Sampel").click()
    page.get_by_role("textbox", name="no Sampel").fill("001")
    page.locator("a").filter(has_text="Select rujukan lab askes").click()
    page.locator("#rujukan_lab_faskes_chosen").get_by_text("LAB RSUP Dr. Hasan Sadikin").click()
    page.get_by_placeholder("Tanggal Sample Dikirim").fill("2025-05-16")
    page.locator("#jenis_pembiayaan_chosen a").click()
    page.locator("#jenis_pembiayaan_chosen").get_by_text("APBD").click()
    page.locator("#hasil_sample").nth(1).check()
    page.locator("#hasil_tsh_chosen a").click()
    page.locator("#hasil_tsh_chosen").get_by_text("Tinggi").click()
    page.locator("#tes_konfirm_chosen a").click()
    page.locator("#tes_konfirm_chosen").get_by_text("Ya").click()
    page.locator("#hasil_tes_konf_chosen a").click()
    page.locator("#hasil_tes_konf_chosen").get_by_text("Tidak Positif HK").click()
    page.locator("a").filter(has_text="Select an Option").click()
    page.locator("#pengobatan_konf_chosen").get_by_text("Tidak").click()
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("radio", name="Ya", exact=True).check()
    page.locator("#keluhan_mtbm_chosen").get_by_role("list").first.click()
    page.locator("#keluhan_mtbm_chosen").get_by_text("Bayi Kuning").click()
    page.get_by_role("spinbutton", name="Umur berapa timbul kuning").click()
    page.get_by_role("spinbutton", name="Umur berapa timbul kuning").fill("1")
    page.get_by_role("textbox", name="Jam timbul kuning pertama kali").click()
    page.get_by_role("textbox", name="Jam timbul kuning pertama kali").fill("23:22")
    page.get_by_role("spinbutton", name="Berat Badan Bayi (GR)").click()
    page.get_by_role("spinbutton", name="Berat Badan Bayi (GR)").fill("2.3")
    page.get_by_role("spinbutton", name="Panjang Bayi (CM)").click()
    page.get_by_role("spinbutton", name="Panjang Bayi (CM)").fill("11.5")
    page.get_by_role("spinbutton", name="Berat Badan Bayi (GR)").click()
    page.get_by_role("spinbutton", name="Berat Badan Bayi (GR)").fill("2400")
    page.get_by_role("spinbutton", name="Lingkar Kepala Bayi (CM)").click()
    page.get_by_role("spinbutton", name="Lingkar Kepala Bayi (CM)").fill("10")
    page.locator("#status_lingkar_kepala_chosen a").click()
    page.locator("#status_lingkar_kepala_chosen").get_by_text("Normal").click()
    page.locator("#status_gizi_bbpb_chosen a").click()
    page.locator("#status_gizi_bbpb_chosen").get_by_text("Normal").click()
    page.locator("#status_gizi_bbu_chosen a").click()
    page.locator("#status_gizi_bbu_chosen").get_by_text("Normal").click()
    page.locator("#status_gizi_pbu_chosen a").click()
    page.locator("#status_gizi_pbu_chosen").get_by_text("Normal").click()
    page.get_by_role("textbox", name="Suhu (Celcius)").click()
    page.get_by_role("textbox", name="Suhu (Celcius)").fill("35.5")
    page.locator("a").filter(has_text="Hipotermi").click()
    page.get_by_role("listitem").filter(has_text="Hipotermi").click()
    page.locator("#saturasi_oksigen_tangan_kanan_pem1").click()
    page.locator("#saturasi_oksigen_tangan_kanan_pem1").fill("1")
    page.locator("#saturasi_oksigen_tangan_kanan_pem2").click()
    page.locator("#saturasi_oksigen_tangan_kanan_pem2").fill("2")
    page.locator("#saturasi_oksigen_tangan_kanan_pem3").click()
    page.locator("#saturasi_oksigen_tangan_kanan_pem3").fill("3")
    page.get_by_role("spinbutton", name="saturasi oksigen tangan kanan").click()
    page.get_by_role("spinbutton", name="saturasi oksigen tangan kanan").fill("90")
    page.locator("#saturasi_oksigen_tangan_kiri_pem1").click()
    page.locator("#saturasi_oksigen_tangan_kiri_pem1").fill("1")
    page.locator("#saturasi_oksigen_tangan_kiri_pem2").click()
    page.locator("#saturasi_oksigen_tangan_kiri_pem2").fill("2")
    page.locator("#saturasi_oksigen_tangan_kiri_pem3").click()
    page.locator("#saturasi_oksigen_tangan_kiri_pem3").fill("3")
    page.locator("#perbedaan_saturasi_oksigen_tangan_kanan_kiri_pem1").click()
    page.locator("#perbedaan_saturasi_oksigen_tangan_kanan_kiri_pem1").fill("1")
    page.locator("#perbedaan_saturasi_oksigen_tangan_kanan_kiri_pem2").click()
    page.locator("#perbedaan_saturasi_oksigen_tangan_kanan_kiri_pem2").fill("2")
    page.locator("#perbedaan_saturasi_oksigen_tangan_kanan_kiri_pem3").click()
    page.locator("#perbedaan_saturasi_oksigen_tangan_kanan_kiri_pem3").fill("3")
    page.locator("a").filter(has_text="Select Hasil skrining PJB").click()
    page.locator("#hasil_skrining_pjb_chosen").get_by_text("Positif").click()
    page.get_by_role("spinbutton", name="Frekuensi Nadi").click()
    page.get_by_role("spinbutton", name="Frekuensi Nadi").fill("100")
    page.locator("a").filter(has_text="Select Kategori Nadi").click()
    page.locator("#kategori_nadi_chosen").get_by_role("list").get_by_text("Normal").click()
    page.get_by_role("spinbutton", name="Frekuensi Nafas (x/menit)").click()
    page.get_by_role("spinbutton", name="Frekuensi Nafas (x/menit)").fill("40")
    page.locator("a").filter(has_text="Lambat").click()
    page.locator("#kategori_nafas_chosen").get_by_role("list").get_by_text("Normal").click()
    page.locator("a").filter(has_text="Select Gerakan Bayi").click()
    page.locator("#gerakan_bayi_chosen").get_by_text("bayi bergerak setelah").click()
    page.get_by_role("radio", name="Bayi Merintih Ya").check()
    page.get_by_role("radio", name="Pernafasan cuping hidung Ya").check()
    page.locator("a").filter(has_text="Select Kulit Bayi").click()
    page.locator("#kulit_bayi_chosen").get_by_text("Pustul").click()
    page.locator("a").filter(has_text="Select Kepala").click()
    page.locator("#kepala_chosen").get_by_text("Normal", exact=True).click()
    page.locator("a").filter(has_text="Select Mata").click()
    page.locator("#mata_chosen").get_by_text("bernanah sedikit").click()
    page.locator("a").filter(has_text="Select hidung").click()
    page.locator("#hidung_chosen").get_by_text("dugaan kelainan").click()
    page.locator("a").filter(has_text="Select Mulut").click()
    page.locator("#mulut_chosen").get_by_text("luka atau keputihan (trush)").click()
    page.locator("a").filter(has_text="Select Dada").click()
    page.locator("#dada_chosen").get_by_text("dugaan kelainan bawaan").click()
    page.locator("a").filter(has_text="Select Perut").click()
    page.locator("#perut_chosen").get_by_text("Kelainan", exact=True).click()
    page.locator("a").filter(has_text="Select cubit_kulit_perut").click()
    page.locator("#cubit_kulit_perut_chosen").get_by_text("lambat (masih sempat terlihat").click()
    page.locator("a").filter(has_text="Select pusar").click()
    page.locator("#pusar_chosen").get_by_text("kemerahan meluas sampai").click()
    page.locator("a").filter(has_text="Select kemerahan_meluas").click()
    page.locator("#kemerahan_meluas_chosen").get_by_text("Tidak").click()
    page.locator("a").filter(has_text="Select Punggung").click()
    page.locator("#punggung_chosen").get_by_text("Lainnya").click()
    page.get_by_role("textbox", name="Lainnya").click()
    page.get_by_role("textbox", name="Lainnya").fill("lainnya")
    page.locator("a").filter(has_text="Select Lubang Anus").click()
    page.locator("#lubang_anus_chosen").get_by_text("Kelainan", exact=True).click()
    page.locator("a").filter(has_text="Select Alat Kelamin").click()
    page.locator("#alat_kelamin_chosen").get_by_text("Kelainan", exact=True).click()
    page.locator("a").filter(has_text="Select Kaki").click()
    page.locator("#kaki_chosen").get_by_text("tidak ada kelainan").click()
    page.locator("a").filter(has_text="Select telapak_tangan_kaki").click()
    page.locator("#telapak_tangan_kaki_chosen").get_by_text("tidak icterus").click()
    page.get_by_role("radio", name="Ibu pernah tes HIV Ya").check()
    page.locator("a").filter(has_text=re.compile(r"^Select hasil_tes_hiv$")).click()
    page.locator("#hasil_tes_hiv_chosen").get_by_text("Positif").click()
    page.locator("div:nth-child(2) > div > .col-md-12 > label").first.click()
    page.get_by_role("radio", name="Apakah ibu dalam pengobatan").check()
    page.get_by_role("radio", name="Bayi pernah tes HIV Ya").check()
    page.locator("a").filter(has_text="Select hasil_tes_hiv_bayi").click()
    page.locator("#hasil_tes_hiv_bayi_chosen").get_by_text("Negatif").click()
    page.get_by_role("radio", name="Bayi saat ini mendapat ASI Ya").check()
    page.get_by_role("radio", name="Bayi pernah mendapat ASI").check()
    page.get_by_role("radio", name="Apakah bayi diberikan").check()
    page.locator("a").filter(has_text="Select susu_yang_diberikan").click()
    page.locator("#susu_yang_diberikan_chosen").get_by_text("tidak sesuai").click()
    page.locator("a").filter(has_text="Select frekuensi_pemberian_susu").click()
    page.locator("#frekuensi_pemberian_susu_chosen").get_by_text("tidak sesuai").click()
    page.locator("a").filter(has_text="Select jumlah_yang_diberikan").click()
    page.locator("#jumlah_yang_diberikan_chosen").get_by_text("tidak sesuai").click()
    page.locator("a").filter(has_text="Select cara_pemberian_susu").click()
    page.locator("#cara_pemberian_susu_chosen").get_by_text("tidak sesuai").click()
    page.locator("a").filter(has_text="Select alat_pemberian_susu").click()
    page.locator("a").filter(has_text="Select cara_membersihkan_alat_minum").click()
    page.locator("#cara_membersihkan_alat_minum_chosen").get_by_text("sesuai", exact=True).click()
    page.locator("a").filter(has_text="Select alat_pemberian_susu").click()
    page.locator("#alat_pemberian_susu_chosen").get_by_text("sesuai", exact=True).click()
    page.locator("a").filter(has_text="Select minuman_tambahan_pengganti").click()
    page.locator("#minuman_tambahan_pengganti_chosen").get_by_text("sesuai", exact=True).click()
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("radio", name="Pencegahan Hipotermi Ya").check()
    page.get_by_role("radio", name="Perawatan Tali Pusar Ya").check()
    page.get_by_role("radio", name="IMD Ya").check()
    page.get_by_role("radio", name="Pencegahan Infeksi Ya").check()
    page.locator("div:nth-child(5) > .row > div > div > .col-md-12 > label").first.click()
    page.get_by_role("textbox", name="Note ASI Eks").click()
    page.get_by_role("textbox", name="Note ASI Eks").fill("notes")
    page.locator("#a_tanda_bahaya_bayi_baru_lahir").get_by_text("Ya", exact=True).click()
    page.locator("#pencegahan_chosen").get_by_role("list").first.click()
    page.locator("#pencegahan_chosen").get_by_text("DPT1").click()
    page.get_by_role("radio", name="Injeksi Vit K Ya").check()
    page.get_by_role("textbox", name="Note Injeksi Vit K").click()
    page.get_by_role("textbox", name="Note Injeksi Vit K").fill("injek")
    page.get_by_role("radio", name="Tetes Mata Antibiotik Ya").check()
    page.get_by_role("textbox", name="Note Tetes Mata Antibiotik").click()
    page.get_by_role("textbox", name="Note Tetes Mata Antibiotik").fill("tetes")
    page.locator("a").filter(has_text=re.compile(r"^Penyakit sangat berat/infeksi bakteri berat$")).click()
    page.locator("#kategori_mtbm_chosen").get_by_text("Infeksi bakteri local").click()
    page.locator("a").filter(has_text=re.compile(r"^Ikterus berat$")).click()
    page.locator("#ikterus_chosen").get_by_text("Ikterus", exact=True).click()
    page.locator("a").filter(has_text=re.compile(r"^Diare Dehidrasi Berat$")).click()
    page.locator("#diare_chosen").get_by_text("Diare dehidrasi ringan/sedang").click()
    page.locator("a").filter(has_text="Mungkin Infeksi HIV").click()
    page.locator("#infeksi_hiv_chosen").get_by_text("Infeksi HIV Tidak Diketahui").click()
    page.locator("#bbu_atau_masalah_asi_chosen a").click()
    page.get_by_role("listitem").filter(has_text="Berat Badan Rendah Menurut").click()
    page.locator("#bbu_atau_masalah_pemberian_minum_chosen a").click()
    page.locator("#bbu_atau_masalah_pemberian_minum_chosen").get_by_text("Berat Badan Tidak Rendah").click()
    page.get_by_role("textbox", name="Diagnosa").click()
    page.get_by_role("textbox", name="Diagnosa").fill("diagnosa sakit")
    page.locator("#kode_icd_chosen").get_by_role("list").first.click()
    page.locator("#kode_icd_chosen").get_by_role("textbox").fill("icd 10")
    page.locator("a").filter(has_text="Select tatalaksana_shk").click()
    page.locator("#ttl_shk_chosen").get_by_text("Pemberian Levotiroksin").click()
    page.get_by_role("spinbutton", name="SHK Usia mulai pengobatan").click()
    page.get_by_role("spinbutton", name="SHK Usia mulai pengobatan").fill("2")
    page.get_by_role("spinbutton", name="Dosis").click()
    page.get_by_role("spinbutton", name="Dosis").fill("2")
    page.get_by_role("textbox", name="PJB Kritis Rujuk Ke.").click()
    page.get_by_role("textbox", name="PJB Kritis Rujuk Ke.").fill("rshs")
    page.locator("a").filter(has_text="Penyakit Sangat Berat/Infeksi").click()
    page.locator("#ttl_infeksi_bakteri_chosen").get_by_text("Memastikan jalan napas bebas/").click()
    page.locator("a").filter(has_text="Ikterus Berat").click()
    page.locator("#ttl_ikterus_berat_chosen").get_by_text("Pertahankan asupan ASI agar").click()
    page.locator("a").filter(has_text="Diare Dehidrasi Berat").click()
    page.locator("#ttl_dehidrasi_berat_chosen").get_by_text("Anjurkan ibu tetap memberikan").click()
    page.locator("a").filter(has_text="Infeksi Terpajan Hiv").click()
    page.locator("#ttl_terpajan_hiv_chosen").get_by_text("Pemberian antiretroviral").click()
    page.locator("#ttl_bbr_asi_chosen a").click()
    page.locator("#ttl_bbr_asi_chosen").get_by_text("Ajari penggunaan cangkir").click()
    page.locator("a").filter(has_text="Berat Berat Badan Rendah").click()
    page.locator("#ttl_bbr_chosen").get_by_text("Mengajarkan cara pemberian").click()
    page.get_by_role("radio", name="Ya", exact=True).first.check()
    page.get_by_role("radio", name="Ya", exact=True).nth(1).check()
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("textbox", name="Imunisasi yang terakhir").click()
    page.get_by_role("textbox", name="Imunisasi yang terakhir").fill("imun tubuh")
    page.get_by_text("Sudah").nth(2).click()
    page.get_by_placeholder("Imunisasi Hb0 Tanggal").fill("2025-05-15")
    page.get_by_placeholder("Imunisasi Hb0 Batch").click()
    page.get_by_placeholder("Imunisasi Hb0 Batch").fill("1")
    page.get_by_role("radio", name="Imunisasi BCG dan OPV O Sudah").check()
    page.get_by_placeholder("Imunisasi BCG dan OPV O Tanggal").fill("2025-05-08")
    page.get_by_placeholder("Imunisasi BCG dan OPV O Batch").click()
    page.get_by_placeholder("Imunisasi BCG dan OPV O Batch").fill("2")
    page.get_by_role("radio", name="Imunisasi DPT HB Hib 1, OpV,").check()
    page.get_by_placeholder("Imunisasi DPT HB Hib 1, OpV,RV 1 PCV 1 Tanggal").fill("2025-05-10")
    page.get_by_placeholder("Imunisasi DPT HB Hib 1, OpV,RV 1 PCV 1 Batch").click()
    page.get_by_placeholder("Imunisasi DPT HB Hib 1, OpV,RV 1 PCV 1 Batch").fill("3")
    page.get_by_role("radio", name="Komunikasi Edukasi &").click()
    page.locator("#note_kie_chosen").get_by_role("list").first.click()
    page.locator("#note_kie_chosen").get_by_text("Gizi").click()
    page.get_by_role("list").filter(has_text=re.compile(r"^Gizi$")).click()
    page.locator("#note_kie_chosen").get_by_text("Penanganan diare di rumah").click()
    page.get_by_role("radio", name="Neonatus dirujuk Ya").check()
    page.get_by_role("textbox", name="Alasan dirujuk").click()
    page.get_by_role("textbox", name="Alasan dirujuk").fill("karena sakit")
    page.locator("a").filter(has_text="Select Dirujuk Ke").click()
    page.locator("#dirujuk_ke_chosen").get_by_text("RS").click()
    page.locator("a").filter(has_text="Select Provinsi").click()
    page.locator("#id_prov_tujuan_rujuk_chosen").get_by_text("JAWA BARAT").click()
    page.locator("a").filter(has_text="Select Kabupaten/Kota").click()
    page.locator("#id_kab_tujuan_rujuk_chosen").get_by_text("KOTA BANDUNG").click()
    page.locator("a").filter(has_text="Select Faskes").click()
    page.locator("#nama_faskes_tujuan_rujukan_chosen").get_by_text("DINKES KOTA BANDUNG").click()
    page.get_by_role("textbox", name="Tgl Konsul Ulang").fill("2025-05-18")
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("checkbox", name="Tidak Mau Menyusu").check()
    page.get_by_text("Kejang Kejang").click()
    page.get_by_text("Lemah", exact=True).click()
    page.get_by_role("checkbox", name="Bayi Merintih atau menangis").check()
    page.get_by_role("checkbox", name="Sesak Nafas").check()
    page.get_by_role("checkbox", name="Tali Pusar Kemerahan").check()
    page.get_by_role("checkbox", name="Demam Panas Tinggi").check()
    page.get_by_role("checkbox", name="Mata Bayi Bernanah").check()
    page.get_by_role("checkbox", name="Diare Buang Air Besar Cair").check()
    page.get_by_role("checkbox", name="Kulit dan mata bayi kuning").check()
    page.get_by_role("checkbox", name="Tinja bayi saat buang air").check()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
