import re
import time
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://ekohort.kemkes.go.id/administrator/login")
    page.get_by_role("textbox", name="Pilih Provinsi").click()
    page.get_by_role("searchbox", name="Search").fill("jawa")
    page.get_by_role("option", name="JAWA BARAT").click()
    klik = page.get_by_role("textbox", name="Pilih Kabupaten")
    kab = page.get_by_role("textbox", name="Pilih Kabupaten").click()
    print(klik)
    for i in range(10):
        print("waiting for kabupaten")
        page.wait_for_timeout(1000)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        page.wait_for_timeout(100)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        kab = page.get_by_role("option", name="KABUPATEN TASIKMALAYA")
        print(kab)
        if kab.is_visible():
            print("kabupaten visible")
            break
    page.get_by_role("option", name="KABUPATEN TASIKMALAYA").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").fill("phone_number")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("password_here")
    page.get_by_role("button", name="Secure login").click()
    page.get_by_role("link", name=" Pelayanan KIA ").click()
    page.get_by_role("link", name=" Pelayanan Anak").click()
    page.get_by_role("link", name=" Tambah Data Anak Baru").click()
    page.get_by_role("textbox", name="NIK Bayi").click()
    page.get_by_role("textbox", name="NIK Bayi").fill("3298091907780002")
    page.get_by_role("textbox", name="Nama Bayi *").click()
    page.get_by_role("textbox", name="Nama Bayi *").fill("bayu gatra")
    page.get_by_role("textbox", name="No Rekam Medis").click()
    page.get_by_role("textbox", name="No Rekam Medis").fill("0023")
    page.locator("a").filter(has_text="Select Jenis Kelamin").click()
    page.locator("#jenkel_chosen").get_by_text("Laki-laki").click()
    page.locator("#id_provinsi2_chosen a").click()
    page.locator("#id_provinsi2_chosen").get_by_role("textbox").fill("jawa")
    page.locator("#id_provinsi2_chosen").get_by_text("JAWA BARAT").click()
    page.locator("#id_kabupaten2_chosen a").click()
    page.locator("#id_kabupaten2_chosen").get_by_text("KABUPATEN TASIKMALAYA").click()
    page.locator("#id_kecamatan2_chosen a").click()
    page.locator("#id_kecamatan2_chosen").get_by_text("SUKARAME").click()
    page.locator("#id_desa2_chosen a").click()
    page.locator("#id_desa2_chosen").get_by_text("SUKARAME").click()
    page.get_by_role("textbox", name="RW").click()
    page.get_by_role("textbox", name="RW").fill("002")
    page.get_by_role("textbox", name="RT").click()
    page.get_by_role("textbox", name="RT").fill("001")
    page.get_by_role("textbox", name="Alamat").click()
    page.get_by_role("textbox", name="Alamat").fill("jl. sukarame no 12")
    page.get_by_role("textbox", name="Nama Ibu *").click()
    page.get_by_role("textbox", name="Nama Ibu *").fill("maemunah")
    page.get_by_role("textbox", name="Tanggal Lahir Ibu *").fill("2000-01-01")
    page.get_by_placeholder("NIK Ibu").click()
    page.get_by_placeholder("NIK Ibu").fill("3278010101990002")
    page.get_by_role("textbox", name="No Handphone / WA", exact=True).click()
    page.get_by_role("textbox", name="No Handphone / WA", exact=True).fill("086762800120")
    page.locator("a").filter(has_text="Pilih Golongan Darah").click()
    page.locator("#gol_darah_ibu_chosen").get_by_text("A", exact=True).click()
    page.locator("#rhesus_ibu_chosen a").click()
    page.locator("#rhesus_ibu_chosen").get_by_text("+").click()
    page.get_by_role("textbox", name="Umur Ibu").click()
    page.get_by_role("textbox", name="Umur Ibu").fill("24")
    page.locator("#etnis").click()
    page.locator("#etnis").fill("                                                                                                                            sunda")
    page.get_by_text("No", exact=True).first.click()
    page.get_by_role("textbox", name="Nama Ayah").click()
    page.get_by_role("textbox", name="Nama Ayah").fill("arda turan")
    page.get_by_role("spinbutton", name="Nik Ayah").click()
    page.get_by_role("spinbutton", name="Nik Ayah").fill("3278091809980004")
    page.get_by_role("textbox", name="No Handphone / WA Ayah").click()
    page.get_by_role("textbox", name="No Handphone / WA Ayah").fill("085176709001")
    page.get_by_label("Step 1").locator("a").filter(has_text="Select Gol Darah").click()
    page.get_by_label("Step 1").locator("#gol_darah_chosen").get_by_text("AB").click()
    page.locator("a").filter(has_text="Pilih Rhesus").click()
    page.locator("#rhesus_suami_chosen").get_by_text("-").click()
    page.get_by_role("textbox", name="Etnis Ayah").click()
    page.get_by_role("textbox", name="Etnis Ayah").fill("                                                                                                                    sulawesi")
    page.get_by_text("No", exact=True).nth(1).click()
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("textbox", name="Jenis Asuransi").click()
    page.get_by_role("textbox", name="Jenis Asuransi").fill("swasta")
    page.get_by_role("textbox", name="Asuransi", exact=True).click()
    page.get_by_role("textbox", name="Asuransi", exact=True).fill("manulife")
    page.get_by_role("textbox", name="Status Kesejahteraan").click()
    page.get_by_role("textbox", name="Status Kesejahteraan").fill("menengah ke atas")
    page.get_by_role("textbox", name="Jam Lahir").click()
    # Klik elemen dropdown pertama yang terlihat
    page.locator("div:visible").nth(0).click()  # Memilih elemen dropdown pertama yang terlihat
    # page.locator("div").filter(has_text="00:0000:0500:1000:1500:2000:").nth(2).click()
    # page.get_by_text("11:39").click()
    page.locator("a").filter(has_text="Select Tipe Tempat Lahir").click()
    page.locator("#tipe_tempat_lahir_chosen").get_by_text("Puskesmas").click()
    page.locator("a").filter(has_text="Select Metode Persalinan").click()
    page.locator("#metode_persalinan_chosen").get_by_text("Tindakan SC").click()
    page.locator("#id_tempat_lahir_chosen a").click()
    page.get_by_role("listitem").filter(has_text="PUSKESMAS TINEWATI").click()
    page.locator("#penolong_persalinan_chosen").get_by_role("list").first.click()
    page.locator("#penolong_persalinan_chosen").get_by_text("Dokter Spesialis Obgyn").click()
    page.get_by_role("spinbutton", name="Jumlah penolong persalinan").click()
    page.get_by_role("spinbutton", name="Jumlah penolong persalinan").fill("2")
    page.locator("a").filter(has_text=re.compile(r"^ELLA NURLAELLA$")).click()
    page.get_by_role("listitem").filter(has_text="ELLA NURLAELLA").click()
    page.locator("#id_penolong_persalinan2_chosen a").click()
    page.locator("#id_penolong_persalinan2_chosen").get_by_text("LIA YULIANI", exact=True).click()
    page.locator("a").filter(has_text="Select Id Penolong Persalinan").click()
    page.locator("#id_penolong_persalinan3_chosen").get_by_text("HANI HARLIA").click()
    page.locator("a").filter(has_text="Select Id Provinsi").click()
    page.get_by_label("Step 2").locator("#id_provinsi_chosen").get_by_role("textbox").fill("jawa")
    page.get_by_role("listitem").filter(has_text="JAWA BARAT").click()
    page.locator("a").filter(has_text="Select Id Kabupaten").click()
    page.locator("a").filter(has_text="Select Id Kabupaten").click()
    page.locator("a").filter(has_text="Select Id Kecamatan").click()
    page.locator("a").filter(has_text="Select Id Kabupaten").click()
    page.get_by_label("Step 2").locator("a").filter(has_text="JAWA BARAT").click()
    page.get_by_role("listitem").filter(has_text="JAWA BARAT").click()
    page.locator("a").filter(has_text="Select Id Kabupaten").click()
    page.get_by_label("Step 2").locator("#id_kabupaten_chosen").get_by_role("textbox").fill("")
    page.get_by_text("Tanggal Lahir Jam Lahir Tempat Kelahiran Rumah Sakit Puskesmas Klinik Kesehatan").click()
    page.locator("a").filter(has_text="Select Id Kabupaten").click()
    page.locator("a").filter(has_text="Select Id Kabupaten").click()
    page.locator("a").filter(has_text="Select Id Kabupaten").click()
    page.get_by_label("Step 2").locator("a").filter(has_text="JAWA BARAT").click()
    page.get_by_role("listitem").filter(has_text="BENGKULU").click()
    page.locator("a").filter(has_text="Select Id Kabupaten").click()
    page.locator("a").filter(has_text="BENGKULU").click()
    page.locator("a").filter(has_text="BENGKULU").click()
    page.locator("a").filter(has_text="BENGKULU").click()
    page.locator("a").filter(has_text="BENGKULU").click()
    page.locator("a").filter(has_text="BENGKULU").click()
    page.get_by_role("listitem").filter(has_text="JAWA BARAT").click()
    page.locator("a").filter(has_text="Select Id Kabupaten").click()
    page.locator("a").filter(has_text="Select Id Desa").click()
    page.locator("a").filter(has_text="Select Id Kecamatan").click()
    page.get_by_role("spinbutton", name="Berat Badan (GR) Saat Lahir").click()
    page.get_by_role("spinbutton", name="Berat Badan (GR) Saat Lahir").fill("2500")
    page.get_by_role("spinbutton", name="Panjang (CM) Saat Lahir").click()
    page.get_by_role("spinbutton", name="Panjang (CM) Saat Lahir").fill("30")
    page.get_by_role("textbox", name="Lingkar Kepala (CM) Saat Lahir").click()
    page.get_by_role("textbox", name="Lingkar Kepala (CM) Saat Lahir").fill("10")
    page.locator("a").filter(has_text="Select Jenis Kelahiran").click()
    page.locator("#jenis_kelahiran_chosen").get_by_text("Tunggal").click()
    page.get_by_role("spinbutton", name="Anak Ke").click()
    page.get_by_role("spinbutton", name="Anak Ke").fill("2")
    page.locator("a").filter(has_text="Select Kondisi Komplikasi").click()
    page.locator("#komplikasi_chosen").get_by_text("Tidak Ada Komplikasi").click()
    page.get_by_role("textbox", name="Keterangan Kondisi Lahir").click()
    page.get_by_role("textbox", name="Keterangan Kondisi Lahir").fill("sehat")
    page.locator(".col-md-12 > label:nth-child(2)").first.click()
    page.locator("div:nth-child(23) > .col-sm-6 > div > .col-md-12 > label:nth-child(2)").click()
    page.get_by_role("radio", name="Apakah Diberikan Resusitasi Ya").check()
    page.locator("#resusitasi").nth(1).check()
    page.get_by_role("radio", name="Diberikan IMD Ya, Kurang dari").check()
    page.locator("#salep_mata").nth(1).check()
    page.get_by_role("radio", name="Vitamin K Injeksi Ya").check()
    page.locator("#hepatitis_b0").nth(1).check()
    page.locator("#pencegahan_chosen").get_by_role("list").first.click()
    page.locator("#pencegahan_chosen").get_by_text("DPT1").click()
    page.locator("a").filter(has_text="Select Gol Darah").click()
    page.get_by_label("Step 2").locator("#gol_darah_chosen").get_by_text("AB").click()
    page.locator("a").filter(has_text="Select Rhesus").click()
    page.locator("#rhesus_chosen").get_by_text("+").click()
    page.locator("a").filter(has_text="Select Id Kabupaten").click()
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("radio", name="Tidak").first.check()
    page.locator("#obat_antitiroid2").check()
    page.locator("a").filter(has_text="Select Riwayat konsumsi").click()
    page.locator("#riwayat_konsumsi_chosen").get_by_text("Ya, >= 3 bulan").click()
    page.get_by_role("textbox", name="Riwayat vaksinasi sebelum/").click()
    page.get_by_role("textbox", name="Riwayat vaksinasi sebelum/").fill("vaksin tetanus")
    page.get_by_role("spinbutton", name="Usia Gestasi Ibu").click()
    page.get_by_role("spinbutton", name="Usia Gestasi Ibu").fill("2")
    page.locator("#riwayat_komplikasi_kehamilan_chosen a").click()
    page.locator("#riwayat_komplikasi_kehamilan_chosen").get_by_text("Tidak Ada").click()
    page.locator("a").filter(has_text="Select Riwayat komplikasi").click()
    page.locator("#riwayat_komp_persalinan_chosen").get_by_text("Tidak Ada").click()
    page.get_by_role("textbox", name="Tatalaksana komplikasi").click()
    page.get_by_role("textbox", name="Tatalaksana komplikasi").fill("tindakan sc")
    page.locator("a").filter(has_text="Select Perilaku Beresiko").click()
    page.locator("#perilaku_beresiko_chosen").get_by_text("Perokok Pasif").click()
    page.get_by_role("textbox", name="Riwayat Penyakit Sebelumnya").click()
    page.get_by_role("textbox", name="Riwayat Penyakit Sebelumnya").fill("sinusitis")
    page.get_by_role("radio", name="Asi Ekslusif Ya").check()
    page.get_by_role("radio", name="Punya Buku KIA Ya").check()
    page.locator("a").filter(has_text="Select Keadaan").click()
    page.locator("#keadaan_chosen").get_by_text("Hidup").click()
    # page.get_by_role("button", name="Choose File").click()
    page.locator("#kode_lembaga_chosen a").click()
    page.get_by_role("listitem").filter(has_text="PUSKESMAS TINEWATI").click()
    # page.get_by_role("menuitem", name="save").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)

# page.get_by_text("Error code").click() jika halaman error