import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://sigizikesga.kemkes.go.id/login_sisfo/")
    page.get_by_role("textbox", name="").fill("name_here")
    page.get_by_role("textbox", name="").press("Tab")
    page.get_by_role("textbox", name="Tampilkan Password ").fill("pass_here")
    page.get_by_role("textbox", name="Tampilkan Password ").press("Tab")
    page.get_by_role("checkbox").press("Tab")
    page.get_by_role("textbox", name="Masukan kata yang terlihat").fill("skuter")
    page.get_by_role("button", name=" Login").click()
    page.get_by_role("link", name="Pelayanan Kesehatan").click()
    page.get_by_role("link", name=" ENTRY ").click()
    page.get_by_role("link", name=" Ibu Hamil ").click()
    page.get_by_role("link", name="Daftar Ibu Hamil", exact=True).click()
    page.get_by_role("button", name=" Cari Data").click()
    page.locator("a:nth-child(3)").first.click()
    page.get_by_role("link", name="+ Tambah Pemeriksaan").click()
    page.locator("#TANGGALUKUR").click()
    page.get_by_role("cell", name="6").first.click()
    page.locator("select[name=\"tenaga_pemeriksa\"]").select_option("1")
    page.locator("select[name=\"riwayat_imun_tt_terakhir\"]").select_option("2")
    page.get_by_placeholder("Contoh : 68.3").click()
    page.get_by_placeholder("Contoh : 170").click()
    page.get_by_role("spinbutton", name="Lingkar Lengan Atas (LILA)").click()
    page.get_by_role("spinbutton", name="Jumlah TTD Diterima (butir)*").click()
    page.locator("select[name=\"td\"]").select_option("1")
    page.locator("select[name=\"tfu_anc\"]").select_option("1")
    page.locator("select[name=\"presentasi_janin\"]").select_option("1")
    page.locator("select[name=\"djj\"]").select_option("1")
    page.locator("select[name=\"diperiksa_usg\"]").select_option("1")
    page.locator("select[name=\"lab_hiv\"]").select_option("2")
    page.locator("select[name=\"lab_hepatitis\"]").select_option("1")
    page.locator("select[name=\"lab_siphilis\"]").select_option("1")
    page.locator("select[name=\"lab_protein_urine\"]").select_option("1")
    page.locator("select[name=\"lab_hb\"]").select_option("1")
    page.locator("select[name=\"lab_gula_sewaktu\"]").select_option("2")
    page.locator("select[name=\"lab_lainnya\"]").select_option("2")
    page.locator("select[name=\"tatalaksana_anemia\"]").select_option("1")
    page.get_by_label("Pre Eklampsia", exact=True).select_option("2")
    page.get_by_label("Tatalaksana Pre Eklampsia").select_option("3")
    page.locator("select[name=\"tatalaksana_kek\"]").select_option("2")
    page.get_by_label("Risiko Masalah Kesehatan Lainnya", exact=True).select_option("3")
    page.get_by_label("Diberikan Tatalaksana Risiko").select_option("1")
    page.locator("select[name=\"konseling\"]").select_option("1")
    page.locator("select[name=\"skrinning_keswa\"]").select_option("1")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
