import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://sigizikesga.kemkes.go.id/login_sisfo/")
    page.get_by_role("textbox", name="").fill("name_here")
    page.get_by_role("textbox", name="").press("Tab")
    page.get_by_role("textbox", name="Tampilkan Password ").fill("pass_here")
    page.get_by_role("textbox", name="Tampilkan Password ").press("Tab")
    page.get_by_role("checkbox").press("Tab")
    page.get_by_role("textbox", name="Masukan kata yang terlihat").fill("rumah")
    page.get_by_role("button", name=" Login").click()
    page.get_by_role("link", name="Pelayanan Kesehatan").click()
    page.get_by_role("link", name=" ENTRY ").click()
    page.get_by_role("link", name=" Ibu Hamil ").click()
    page.get_by_role("link", name="Tambah Ibu Hamil").click()
    page.get_by_role("textbox", name="NIK", exact=True).click()
    page.get_by_role("textbox", name="NIK", exact=True).fill("3278071709990003")
    page.get_by_placeholder("Kehamilan ke").click()
    page.get_by_placeholder("Kehamilan ke").fill("1")
    page.locator("#TL").click()
    page.get_by_role("cell", name="May").click()
    page.get_by_role("cell", name="2025").click()
    page.get_by_role("cell", name="«").click()
    page.get_by_role("cell", name="«").click()
    page.get_by_text("1999").click()
    page.get_by_text("Sep").click()
    page.get_by_role("cell", name="19", exact=True).click()
    page.get_by_role("textbox", name="Nomor Kartu Keluarga").click()
    page.get_by_role("textbox", name="Nomor Kartu Keluarga").fill("3278019809980003")
    page.get_by_role("textbox", name="Nama", exact=True).click()
    page.get_by_role("textbox", name="Nama", exact=True).fill("Narnia")
    page.get_by_role("spinbutton", name="Berat Badan Sebelum Hamil (kg").click()
    page.get_by_role("spinbutton", name="Berat Badan Sebelum Hamil (kg").fill("45")
    page.get_by_role("spinbutton", name="Tinggi Badan (cm)*").click()
    page.get_by_role("spinbutton", name="Tinggi Badan (cm)*").fill("155")
    page.get_by_role("spinbutton", name="LiLA (cm)*").click()
    page.get_by_role("spinbutton", name="LiLA (cm)*").fill("26")
    page.get_by_role("spinbutton", name="IMT Sebelum Hamil atau IMT").click()
    page.get_by_role("spinbutton", name="IMT Sebelum Hamil atau IMT").click()
    page.get_by_role("form").locator("div").filter(has_text="IMT Sebelum Hamil atau IMT").click()
    page.get_by_role("spinbutton", name="IMT Sebelum Hamil atau IMT").click()
    page.locator("#status_kek_text").click()
    page.locator("input[name=\"jarak_tahun\"]").click()
    page.locator("#hpht").click()
    page.get_by_role("cell", name="«").click()
    page.get_by_role("cell", name="1", exact=True).first.click()
    page.locator("#hpl").click()
    page.locator("select[name=\"darah\"]").select_option("AB")
    page.locator("select[name=\"lab_rhesus\"]").select_option("positif")
    page.locator("textarea[name=\"penyakit\"]").click()
    page.locator("textarea[name=\"penyakit\"]").fill("-")
    page.locator("textarea[name=\"alergi\"]").click()
    page.locator("textarea[name=\"alergi\"]").fill("udang")
    page.get_by_role("radio", name="Tidak").check()
    page.locator("select[name=\"jaminan\"]").select_option("2")
    page.get_by_role("textbox", name="No. JKN").click()
    page.get_by_role("textbox", name="No. JKN").fill("01111982")
    page.get_by_role("textbox", name="Faskes TK").click()
    page.get_by_role("textbox", name="Faskes TK").fill("ciseda")
    page.get_by_role("textbox", name="Faskes Rujukan").click()
    page.get_by_role("textbox", name="Faskes Rujukan").fill("puskesmas")
    page.locator("select[name=\"pendidikan\"]").select_option("Sarjana")
    page.get_by_role("textbox", name="Pekerjaan").click()
    page.get_by_role("textbox", name="Pekerjaan").fill("programmer")
    page.get_by_role("textbox", name="Nama Suami").click()
    page.get_by_role("textbox", name="Nama Suami").fill("Adriana qolbi")
    page.get_by_role("textbox", name="NIK Suami").click()
    page.get_by_role("textbox", name="NIK Suami").fill("3278091809970005")
    page.get_by_role("textbox", name="Nomor Telepon/HP Suami").click()
    page.get_by_role("textbox", name="Nomor Telepon/HP Suami").fill("084149802141")
    page.get_by_title("JAWA BARAT").click()
    page.get_by_role("treeitem", name="JAWA BARAT").click()
    page.get_by_title("KAB KAB TASIKMALAYA").click()
    page.get_by_role("treeitem", name="KAB KAB TASIKMALAYA").click()
    page.get_by_title("SINGAPARNA").click()
    page.get_by_role("treeitem", name="SINGAPARNA").click()
    page.get_by_title("TINEWATI").click()
    page.get_by_role("treeitem", name="TINEWATI").click()
    page.get_by_title("SUKAASIH").click()
    page.get_by_role("treeitem", name="SUKAASIH").click()
    page.get_by_role("textbox", name="Alamat Lengkap").click()
    page.get_by_role("textbox", name="Alamat Lengkap").fill("jl. singaparna no 12")
    page.get_by_role("textbox", name="RT", exact=True).click()
    page.get_by_role("textbox", name="RT", exact=True).fill("002")
    page.get_by_role("textbox", name="RW").click()
    page.get_by_role("textbox", name="RW").fill("009")
    # page.get_by_role("button", name="simpan").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
