import re
import time
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://sigizikesga.kemkes.go.id/login_sisfo/")
    page.get_by_role("textbox", name="").click()
    page.get_by_role("textbox", name="").fill("name_here")
    page.get_by_role("textbox", name="Tampilkan Password ").click()
    page.get_by_role("textbox", name="Tampilkan Password ").fill("pass_here")
    page.get_by_role("textbox", name="Masukan kata yang terlihat").click()
    page.get_by_role("textbox", name="Masukan kata yang terlihat").fill("bendera")
    page.get_by_role("button", name=" Login").click()
    page.get_by_role("link", name="Pelayanan Kesehatan").click()
    page.get_by_role("link", name=" ENTRY ").click()
    # time.sleep(1)
    # expect(page.get_by_text("Welcome")).to_be_visible() 
    # page_content = page.content()
    # with open("page.html", "w", encoding="utf-8") as f:
    #     f.write(page_content) 
    # expect(page.get_by_role("link", name=" Balita ")).to_be_visible()
    page.get_by_role("link", name="Balita", class_name="menu-text green").click(force=True)
    page.get_by_text("Tambah Balita").click()
    # page.get_by_role("link", name="Tambah Balita").click()
    # expect(page.locator("#sidebar")).to_contain_text("Balita")
    page.get_by_placeholder("Anak ke").click()
    page.get_by_placeholder("Anak ke").fill("1")
    page.locator("#TL").click()
    page.get_by_role("cell", name="1", exact=True).first.click()
    page.get_by_role("radio", name="Perempuan").check()
    page.get_by_role("textbox", name="Nomor Kartu Keluarga").click()
    page.get_by_role("textbox", name="Nomor Kartu Keluarga").fill("3278091706690001")
    page.locator("#nonik").check()
    page.get_by_role("textbox", name="Nama", exact=True).click()
    page.get_by_role("textbox", name="Nama", exact=True).fill("Raisya avisha")
    page.get_by_placeholder("dalam minggu").click()
    page.get_by_placeholder("dalam minggu").fill("40")
    page.get_by_placeholder("Contoh : 4.3").click()
    page.get_by_placeholder("Contoh : 4.3").fill("2.5")
    page.get_by_placeholder("Contoh : 70").click()
    page.get_by_placeholder("Contoh : 70").fill("40")
    page.get_by_placeholder("Contoh : 33").click()
    page.get_by_placeholder("Contoh : 33").fill("14")
    page.get_by_role("form").locator("div").filter(has_text="Buku KIA* Ya Tidak").get_by_label("Ya").check()
    page.get_by_role("form").locator("div").filter(has_text="Buku KIA Bayi Kecil* Ya Tidak").get_by_label("Ya").check()
    page.get_by_role("form").locator("div").filter(has_text="IMD Ya Tidak").get_by_label("Tidak").check()
    page.get_by_role("textbox", name="Nama Orangtua").click()
    page.get_by_role("textbox", name="Nama Orangtua").fill("rahmansyah")
    page.get_by_role("textbox", name="NIK Orangtua").click()
    page.get_by_role("textbox", name="NIK Orangtua").fill("3279181909970002")
    page.get_by_role("textbox", name="Nomor Telepon/HP Orangtua").click()
    page.get_by_role("textbox", name="Nomor Telepon/HP Orangtua").fill("086765290981")
    page.get_by_title("JAWA BARAT").click()
    page.get_by_role("treeitem", name="JAWA BARAT").click()
    page.get_by_title("KAB KAB TASIKMALAYA").click()
    page.get_by_role("treeitem", name="KAB KAB TASIKMALAYA").click()
    page.get_by_title("SINGAPARNA").click()
    page.get_by_role("treeitem", name="SINGAPARNA").click()
    page.get_by_title("TINEWATI").click()
    page.get_by_role("treeitem", name="TINEWATI").click()
    page.get_by_title("SUKAASIH").click()
    page.get_by_role("treeitem", name="SUKAASIH").click()
    page.get_by_title("-- Silahkan Pilih --").click()
    page.get_by_role("treeitem", name="CARIWUH").click()
    page.get_by_role("textbox", name="Alamat Lengkap").click()
    page.get_by_role("textbox", name="Alamat Lengkap").fill("jl. diponegoro rt 1 rw 10 no 102")
    page.get_by_role("textbox", name="RT", exact=True).click()
    page.get_by_role("textbox", name="RT", exact=True).fill("001")
    page.get_by_role("textbox", name="RW").click()
    page.get_by_role("textbox", name="RW").fill("010")
    # page.get_by_role("button", name="Simpan").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
