import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://ekohort.kemkes.go.id/administrator/login")
    page.get_by_role("textbox", name="Pilih Provinsi").click()
    page.get_by_role("option", name="JAWA BARAT").click()
    klik = page.get_by_role("textbox", name="Pilih Kabupaten")
    kab = page.get_by_role("textbox", name="Pilih Kabupaten").click()
    print(klik)
    for i in range(10):
        print("waiting for kabupaten")
        page.wait_for_timeout(1000)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        page.wait_for_timeout(100)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        kab = page.get_by_role("option", name="KABUPATEN TASIKMALAYA")
        print(kab)
        if kab.is_visible():
            print("kabupaten visible")
            break
    page.get_by_role("option", name="KABUPATEN TASIKMALAYA").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").fill("081224600500")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("123456")
    page.get_by_role("button", name="Secure login").click()
    page.get_by_role("link", name=" Pelayanan KIA ").click()
    page.get_by_role("link", name=" Pelayanan Ibu").click()
    page.locator("button:nth-child(11)").first.click()
    page.get_by_role("button", name=" Mulai Monitoring").click()
    page.get_by_role("link", name=" Tambahkan Data Pelayanan").click()
    page.get_by_role("spinbutton", name="ID Ibu").click()
    page.get_by_role("textbox", name="Nama Ibu").click()
    page.get_by_role("textbox", name="HPHT").click()
    page.get_by_role("textbox", name="HPL").click()
    page.get_by_role("spinbutton", name="Usia Kehamilan (Minggu)").click()
    page.get_by_role("spinbutton", name="Kedatangan Ke - (*)").click()
    page.get_by_role("spinbutton", name="Kedatangan Ke - (*)").fill("2")
    page.locator("a").filter(has_text="Trimester").click()
    page.get_by_role("listitem").filter(has_text="Trimester 2").click()
    page.locator("a").filter(has_text="Select Kunjungan K").click()
    page.locator("#kunjungan_k_chosen").get_by_text("K2").click()
    page.locator("a").filter(has_text="Select Cara Masuk").click()
    page.locator("#cara_masuk_chosen").get_by_text("Rujukan Praktek Dokter").click()
    page.locator("input[name=\"nama_faskes_perujuk\"]").click()
    page.locator("input[name=\"nama_faskes_perujuk\"]").fill("bidan marlina")
    page.get_by_role("radio", name="Ya").first.check()
    page.locator("#row_kia_lengkap").get_by_role("radio", name="Ya").check()
    page.locator("a").filter(has_text="Select Lokasi Screening").click()
    page.locator("#lokasi_chosen").get_by_text("Poskesdes").click()
    page.locator("a").filter(has_text="PUSKESMAS TINEWATI").click()
    page.locator("#kode_lembaga_chosen").get_by_role("textbox").fill("tin")
    page.get_by_role("listitem").filter(has_text="PUSKESMAS TINEWATI").click()
    page.locator("a").filter(has_text="Select Status Lembaga").click()
    page.locator("#status_lembaga_chosen").get_by_text("Pemerintah").click()
    page.locator("a").filter(has_text=re.compile(r"^Bidan$")).click()
    page.get_by_role("listitem").filter(has_text=re.compile(r"^Bidan$")).click()
    page.locator("#id_nakes_chosen a").click()
    page.get_by_role("listitem").filter(has_text="ELLA NURLAELLA").click()
    page.get_by_role("radio", name="Ada", exact=True).check()
    page.locator("input[name=\"keluhan_ibu\"]").click()
    page.locator("input[name=\"keluhan_ibu\"]").fill("mual dan muntah")
    page.get_by_role("spinbutton", name="Berat Badan Saat Ini (KG) (*)").click()
    page.get_by_role("spinbutton", name="Berat Badan Saat Ini (KG) (*)").fill("49")
    page.get_by_role("spinbutton", name="Tinggi Badan (CM)").click()
    page.get_by_role("spinbutton", name="LILA (CM)(*)").click()
    page.get_by_role("spinbutton", name="LILA (CM)(*)").fill("20")
    page.locator("a").filter(has_text="Select Status Gizi Sebelumnya").click()
    page.locator("#status_gizi_chosen").get_by_text("Normal").click()
    page.locator("#usg_konjungtiva").first.check()
    page.locator("#usg_sklera").first.check()
    page.locator("#usg_kulit").first.check()
    page.locator("#usg_leher").first.check()
    page.locator("#usg_gigi_dan_mulut").first.check()
    page.locator("#usg_tht").first.check()
    page.locator("#usg_jantung").first.check()
    page.locator("#usg_paru").first.check()
    page.locator("#usg_perut").first.check()
    page.locator("#usg_tungkai").first.check()
    page.locator("#usg_tungkai_bawah").first.check()
    page.get_by_role("radio", name="Tidak", exact=True).nth(2).check()
    page.locator("a").filter(has_text="Tidak Diperiksa").click()
    page.locator("#refleks_patella_chosen").get_by_text("+").click()
    page.get_by_role("textbox", name="Nadi (x/menit) (*)").click()
    page.get_by_role("textbox", name="Nadi (x/menit) (*)").fill("90")
    page.get_by_role("textbox", name="Respiratory Rate (x/menit) (*)").click()
    page.get_by_role("textbox", name="Respiratory Rate (x/menit) (*)").fill("30")
    page.get_by_role("spinbutton", name="Suhu Badan (Celcius)").click()
    page.get_by_role("textbox", name="Respiratory Rate (x/menit) (*)").click()
    page.get_by_role("textbox", name="Respiratory Rate (x/menit) (*)").fill("20")
    page.get_by_role("spinbutton", name="Suhu Badan (Celcius)").click()
    page.get_by_role("spinbutton", name="Suhu Badan (Celcius)").fill("36")
    page.get_by_role("spinbutton", name="Tekanan Darah (Sis) (*)").click()
    page.get_by_role("spinbutton", name="Tekanan Darah (Sis) (*)").fill("120")
    page.get_by_role("spinbutton", name="Tekanan Darah (Di)").click()
    page.get_by_role("spinbutton", name="Tekanan Darah (Di)").fill("80")
    page.get_by_role("spinbutton", name="MAP").click()
    page.get_by_role("radio", name="Ya").nth(3).check()
    page.get_by_role("spinbutton", name="Tinggi Fundus Uteri (CM) (*)").click()
    page.get_by_role("spinbutton", name="Tinggi Fundus Uteri (CM) (*)").fill("2")
    page.get_by_role("radio", name="USG(*) Ya").check()
    page.locator("a").filter(has_text="Dokter Umum").click()
    page.locator("#nakes_pemeriksa_chosen").get_by_text("Dokter SpOG").click()
    page.locator("a").filter(has_text="Select Nama Nakes").click()
    page.locator("a").filter(has_text="Select Nama Nakes").click()
    page.get_by_role("textbox", name="USG Gs (cm)").click()
    page.get_by_role("textbox", name="USG Gs (cm)").fill("3")
    page.get_by_role("textbox", name="USG Crl (cm)").click()
    page.get_by_role("textbox", name="USG Crl (cm)").fill("4")
    page.get_by_role("textbox", name="USG DJJ (dpp)").click()
    page.get_by_role("textbox", name="USG DJJ (dpp)").fill("2")
    page.get_by_role("textbox", name="USG BPD").click()
    page.get_by_role("textbox", name="USG BPD").fill("3")
    page.get_by_role("textbox", name="USG HC").click()
    page.get_by_role("textbox", name="USG HC").fill("4")
    page.get_by_role("textbox", name="USG AC").click()
    page.get_by_role("textbox", name="USG AC").fill("5")
    page.get_by_role("textbox", name="USG FL").click()
    page.get_by_role("textbox", name="USG FL").fill("1")
    page.get_by_role("textbox", name="USG SDP Ketuban").click()
    page.get_by_role("textbox", name="USG SDP Ketuban").fill("2")
    page.locator("#usg_taksiran_br_janin_chosen a").click()
    page.locator("#usg_taksiran_br_janin_chosen").get_by_text("Sesuai").click()
    page.get_by_role("textbox", name="USG Usia Kehamilan (minggu)").click()
    page.get_by_role("textbox", name="USG Usia Kehamilan (minggu)").fill("11")
    page.get_by_role("textbox", name="USG Letak Janin").click()
    page.get_by_role("textbox", name="USG Letak Janin").fill("2")
    page.get_by_role("textbox", name="USG Presentasi").click()
    page.get_by_role("textbox", name="USG Presentasi").fill("3")
    page.get_by_role("textbox", name="Taksiran Kehamilan").click()
    page.get_by_role("textbox", name="Taksiran Kehamilan").fill("3")
    page.get_by_role("textbox", name="Keterangan Tambahan").click()
    page.get_by_role("textbox", name="Keterangan Tambahan").fill("                                                                                    keterangan")
    page.get_by_role("region").click()
    page.get_by_text("Select Processing dropped").click()
    page.get_by_role("button", name="Choose File").click()
    page.locator("#janin_chosen a").click()
    page.locator("#janin_chosen").get_by_text("Tunggal").click()
    page.locator("#djj_kondisi_chosen a").click()
    page.locator("#djj_kondisi_chosen").get_by_role("list").get_by_text("Normal").click()
    page.get_by_role("spinbutton", name="Detak Jantung Janin (x/menit").click()
    page.get_by_role("spinbutton", name="Detak Jantung Janin (x/menit").fill("120")
    page.locator("#posisi_janin_chosen a").click()
    page.locator("#posisi_janin_chosen").get_by_text("Normal").click()
    page.locator("a").filter(has_text="Masuk PAP").first.click()
    page.get_by_role("listitem").filter(has_text=re.compile(r"^Masuk PAP$")).click()
    page.get_by_role("spinbutton", name="Taksiran Berat Janin Taksiran").click()
    page.get_by_role("spinbutton", name="Taksiran Berat Janin Taksiran").fill("1")
    page.locator("#presentasi_chosen a").click()
    page.get_by_role("spinbutton", name="Taksiran Berat Janin Taksiran").click()
    page.get_by_role("spinbutton", name="Taksiran Berat Janin Taksiran").fill("100")
    page.locator("#presentasi_chosen a").click()
    page.get_by_role("listitem").filter(has_text="Kepala").click()
    page.get_by_role("list").filter(has_text=re.compile(r"^$")).first.click()
    page.locator("#komplikasi_chosen").get_by_text("Lain lain").click()
    page.get_by_role("textbox", name="Komplikasi Lain-lain:").click()
    page.get_by_role("textbox", name="Komplikasi Lain-lain:").fill("komplikasi")
    page.get_by_role("menuitem", name="Next").click()
    page.locator("#pemeriksaan_covid").nth(1).check()
    page.get_by_role("radio", name="Ya", exact=True).first.check()
    page.get_by_role("spinbutton", name="Hasil Pemeriksaan HB (Gr/Dl)").click()
    page.get_by_role("spinbutton", name="Hasil Pemeriksaan HB (Gr/Dl)").fill("11")
    page.locator("div:nth-child(3) > div > div > .col-md-12 > label:nth-child(2)").first.click()
    page.locator("#reduksi").nth(1).check()
    page.locator("#infeksi").nth(1).check()
    page.get_by_role("radio", name="Dilakukan Pemeriksaan VDRL (").check()
    page.locator("#hasil_vdlr_chosen a").click()
    page.locator("#hasil_vdlr_chosen").get_by_text("+").click()
    page.locator("#dilakukan_hiv").nth(1).check()
    page.locator("#lab_tb").nth(1).check()
    page.locator("#lab_malaria").nth(1).check()
    page.locator("#dilakukan_hepb").nth(1).check()
    page.locator("#dilakukan_thalasemia").nth(1).check()
    page.get_by_role("textbox", name="Hasil Lab Lainnya").click()
    page.get_by_role("textbox", name="Hasil Lab Lainnya").fill("hasil lab lainnya")
    page.get_by_role("textbox", name="Diagnosa").click()
    page.get_by_role("textbox", name="Diagnosa").fill("diagnosa dokter")
    page.locator("#status_tt_chosen a").click()
    page.locator("#status_tt_chosen").get_by_text("TT Ke 1").click()
    page.get_by_role("radio", name="Pemberian Imunisasi TT Ya").check()
    page.locator("a").filter(has_text="Pilih Imunisasi").click()
    page.locator("#imunisasi_tt_chosen").get_by_text("TT3").click()
    page.locator("input[name=\"tanggal_imunisasi_tt\"]").fill("2025-05-07")
    page.get_by_role("radio", name="Ya", exact=True).nth(1).check()
    page.locator("a").filter(has_text="Select Tribulan Ke").click()
    page.locator("#pemberian_covid_ke_chosen").get_by_text("COVID-19 ke-1").click()
    page.locator("input[name=\"tanggal_imunisasi_covid\"]").fill("2025-05-01")
    page.get_by_role("menuitem", name="Next").click()
    page.locator("#tatalaksana_anemia").nth(1).check()
    page.locator("#tatalaksana_anemia").nth(1).check()
    page.locator("#tatalaksana_hipertensi").first.check()
    page.locator("#pantau_tekanan_darah").first.check()
    page.locator("#pantau_protein_urine").first.check()
    page.locator("#pantau_kondisi_janin").first.check()
    page.get_by_role("textbox").click()
    page.get_by_role("textbox").fill("lainlain")
    page.locator("#tatalaksana_preeklampsia").nth(1).check()
    page.locator("#diabetes").nth(1).check()
    page.locator("#tatalaksana_kek").first.check()
    page.locator("#pemberian_mt").first.check()
    page.locator("#pemberian_mt").first.press("2")
    page.get_by_role("textbox", name="Jumlah MT yang telah diberikan").click()
    page.get_by_role("textbox", name="Jumlah MT yang telah diberikan").fill("2")
    page.get_by_role("textbox", name="Jumlah MT yang telah didapatkan").click()
    page.get_by_role("textbox", name="Jumlah MT yang telah didapatkan").fill("2")
    page.locator("a").filter(has_text="Select Jenis MT").click()
    page.locator("#jenis_mt_chosen").get_by_text("MT Pabrikan").click()
    page.locator("a").filter(has_text="Select Sumber MT yang akan").click()
    page.locator("#sumber_mt_diberikan_chosen").get_by_text("APBD").click()
    page.locator("div:nth-child(9) > div:nth-child(10) > div > .col-md-12 > label").first.click()
    page.locator("input[name=\"tata_laksana_kek_lain\"]").click()
    page.locator("input[name=\"tata_laksana_kek_lain\"]").fill("lainlain")
    page.locator("#tatalaksana_obesitas").first.check()
    page.locator("#edukasi_gizi_ibu_hamil").first.check()
    page.locator("input[name=\"tata_laksana_obesitas_lain\"]").click()
    page.locator("input[name=\"tata_laksana_obesitas_lain\"]").fill("gula darah")
    page.locator("#tatalaksana_infeksi").nth(1).check()
    page.locator("#tatalaksana_jantung").nth(1).check()
    page.locator("#tatalaksana_jantung").nth(1).check()
    page.locator("#tatalaksana_hiv").nth(1).check()
    page.get_by_role("radio", name="TataLaksana TB Ya").check()
    page.locator("a").filter(has_text="Select Obat TB").click()
    page.locator("#obat_tb_chosen").get_by_text("Pyrazinamid").click()
    page.get_by_role("textbox", name="Sisa Obat").click()
    page.get_by_role("textbox", name="Sisa Obat").fill("tbc")
    page.get_by_role("textbox", name="Lainnya").click()
    page.get_by_role("textbox", name="Lainnya").fill("tbc lain")
    page.locator("#ttl_hepatitis").nth(1).check()
    page.get_by_role("radio", name="Tatalaksana Sifilis Ya").check()
    page.locator("input[name=\"obat_ttl_sifilis\"]").click()
    page.locator("input[name=\"obat_ttl_sifilis\"]").fill("obat sifil")
    page.locator("input[name=\"ttl_sifilis_lain\"]").click()
    page.locator("input[name=\"ttl_sifilis_lain\"]").fill("obat lain")
    page.locator("#tatalaksana_malaria").nth(1).check()
    page.locator("#tatalaksana_malaria").first.check()
    page.locator("#kelambu_berinsektisida").nth(1).check()
    page.locator("#tata_laksana_obat_malaria_chosen a").click()
    page.locator("#tata_laksana_obat_malaria_chosen").get_by_text("Amodiakuin").click()
    page.locator("input[name=\"lainnya_malaria\"]").click()
    page.locator("input[name=\"lainnya_malaria\"]").fill("lain")
    page.locator("#tatalaksana_lainnya").first.check()
    page.locator("input[name=\"jenis_tatalaksana_lain\"]").click()
    page.locator("input[name=\"jenis_tatalaksana_lain\"]").fill("jenis tatalaksana")
    page.locator("input[name=\"isian_tatalaksana_lain\"]").click()
    page.locator("input[name=\"isian_tatalaksana_lain\"]").fill("tatalaksana lain")
    page.get_by_label("Step 3").locator("div").filter(has_text="Rujuk Rujuk Ya Tidak Faskes").get_by_label("Ya").check()
    page.locator("a").filter(has_text="Select an Option").click()
    page.locator("#faskes_rujukan_chosen").get_by_text("Puskesmas PONED").click()
    page.locator("a").filter(has_text="KABUPATEN TASIKMALAYA").click()
    page.get_by_role("listitem").filter(has_text="KABUPATEN TASIKMALAYA").click()
    page.locator("a").filter(has_text="BIDAN EUIS KARTINA").click()
    page.get_by_role("listitem").filter(has_text="BIDAN EUIS KARTINA").click()
    page.get_by_role("radio", name="Konseling Ya").check()
    page.locator("#a_konseling").get_by_role("radio", name="Ya").check()
    page.locator("#a_tanda_bahaya_kehamilan").get_by_role("radio", name="Ya").check()
    page.locator("#a_tanda_bahaya_persalinan").get_by_role("radio", name="Ya").check()
    page.locator("#a_konseling_lainnya").get_by_role("radio", name="Ya").check()
    page.locator("#a_konseling_p4k").get_by_role("radio", name="Ya").check()
    page.locator("#a_konseling_gizi_ibu_hamil").get_by_role("radio", name="Ya").check()
    page.locator("#a_konseling_phbs").get_by_role("radio", name="Ya").check()
    page.locator("#konseling_lainnya").click()
    page.locator("#konseling_lainnya").fill("konseling lain")
    page.get_by_role("radio", name="DiCatat Di Buku KIA? Ya").check()
    page.get_by_role("radio", name="Diikutkan dalam kelas ibu").check()
    page.get_by_role("radio", name="Diberikan Kapsul Minyak Ikan").check()
    page.get_by_role("radio", name="Dilakukan Perawatan Payudara").check()
    page.get_by_role("radio", name="Diikutkan dalam kelas Senam").check()
    page.locator("#cek_pelayanan_lainnya").first.check()
    page.locator("#pelayanan_lainnya").click()
    page.locator("#pelayanan_lainnya").fill("pelayanan lain")
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("textbox", name="Tanggal ANC Selanjutnya").click()
    page.get_by_text("31", exact=True).click()
    page.get_by_role("checkbox", name="Multipara dengan kehamilan").check()
    page.get_by_role("checkbox", name="Kehamilan dengan teknologi").check()
    page.get_by_role("checkbox", name="Usia >= 35 tahun").check()
    page.get_by_role("checkbox", name="Nulipara").check()
    page.get_by_text("Multipara jarak kehamilan").click()
    page.get_by_role("checkbox", name="Riwayat preeklampsia pada ibu").check()
    page.get_by_role("checkbox", name="Obesitas sebelum hamil (MT >").check()
    page.get_by_role("checkbox", name="Kehamilan multiple").check()
    page.get_by_role("checkbox", name="Multipara dengan riwayat").check()
    page.get_by_role("checkbox", name="Diabetes dalam kehamilan").check()
    page.get_by_role("checkbox", name="Hipertensi kronik").check()
    page.get_by_role("checkbox", name="Penyakit Ginjal").check()
    page.get_by_role("checkbox", name="Penyakit Auto Imun, SLE").check()
    page.get_by_role("checkbox", name="Anti phospolipid syndrom*").check()
    page.get_by_role("checkbox", name="Pemeriksaan Fisik").check()
    page.get_by_role("checkbox", name="Mean Arterial Presure > 90").check()
    page.get_by_role("checkbox", name="Proteinuria (urin celup > +1").check()
    page.get_by_role("checkbox", name="Riwayat SC").check()
    page.get_by_role("checkbox", name="Melahirlkan prematur").check()
    page.get_by_role("checkbox", name="Abortus berulang").check()
    page.get_by_role("checkbox", name="Protein Urine +").check()
    page.get_by_role("checkbox", name="Hipertensi", exact=True).check()
    page.get_by_role("checkbox", name="Anemia Berat").check()
    page.get_by_role("checkbox", name="Anemia Sedang").check()
    page.get_by_role("checkbox", name="Anemia Ringan").check()
    page.get_by_role("checkbox", name="Kehamilan Ganda").check()
    page.get_by_role("checkbox", name="Paritas >").check()
    page.get_by_role("checkbox", name="Usia <18 tahun").check()
    page.get_by_role("checkbox", name="Usia >35 tahun").check()
    page.get_by_role("checkbox", name="Penyakit Malaria").check()
    page.get_by_role("checkbox", name="Serologi+").check()
    page.get_by_role("checkbox", name="HepB+").check()
    page.get_by_text("KEK (Kekurangan Energi Kronis").click()
    page.get_by_role("checkbox", name="Suhu diluar batas normal").check()
    page.get_by_role("checkbox", name="Tuberculosis").check()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
