import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://ekohort.kemkes.go.id/administrator/login")
    page.get_by_role("textbox", name="Pilih Provinsi").click()
    page.get_by_role("option", name="JAWA BARAT").click()
    klik = page.get_by_role("textbox", name="Pilih Kabupaten")
    kab = page.get_by_role("textbox", name="Pilih Kabupaten").click()
    print(klik)
    for i in range(10):
        print("waiting for kabupaten")
        page.wait_for_timeout(1000)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        page.wait_for_timeout(100)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        kab = page.get_by_role("option", name="KABUPATEN TASIKMALAYA")
        print(kab)
        if kab.is_visible():
            print("kabupaten visible")
            break
    page.get_by_role("option", name="KABUPATEN TASIKMALAYA").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").fill("phone_number")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("password_here")
    page.get_by_role("button", name="Secure login").click()
    page.get_by_role("link", name=" Pelayanan KIA ").click()
    page.get_by_role("link", name=" Pelayanan Ibu").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.locator("td:nth-child(2) > button:nth-child(15)").first.click()
    page.get_by_role("button", name=" Mulai Monitoring").click()
    page.get_by_role("link", name=" Tambahkan Pnc Ibu Hamil Baru").click()
    page.get_by_role("spinbutton", name="ID Ibu").click()
    page.get_by_role("textbox", name="Nama Ibu").click()
    page.get_by_role("textbox", name="Tanggal Bersalin").fill("2025-05-21")
    page.get_by_role("spinbutton", name="Hari ke Sejak Melahirkan").click()
    page.get_by_role("textbox", name="Tanggal Bersalin").fill("2025-05-01")
    page.get_by_role("spinbutton", name="Hari ke Sejak Melahirkan").click()
    page.locator("a").filter(has_text="Pilih Kunjungan KF").click()
    page.locator("#kunjungan_chosen").get_by_text("KF2").click()
    page.locator("a").filter(has_text="Pilih Cara Masuk").click()
    page.locator("#cara_masuk_chosen").get_by_text("Rujukan Praktek Bidan").click()
    page.get_by_role("textbox", name="Tanggal PNC").fill("2025-05-01")
    page.get_by_label("Step 1").get_by_text("Ya", exact=True).click()
    page.locator("a").filter(has_text="Pilih Lokasi Screening").click()
    page.locator("#lokasi_chosen").get_by_text("Poskesdes").click()
    page.locator("a").filter(has_text="Poskesdes").click()
    page.locator("#lokasi_chosen").get_by_text("Puskesmas").click()
    page.locator("a").filter(has_text="PUSKESMAS TINEWATI").click()
    page.get_by_role("listitem").filter(has_text="PUSKESMAS TINEWATI").click()
    page.locator("a").filter(has_text="Pilih Nakes").click()
    page.locator("#nakes_chosen").get_by_text("Bidan", exact=True).click()
    page.locator("#id_nakes_chosen a").click()
    page.get_by_role("listitem").filter(has_text="ELLA NURLAELLA").click()
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("spinbutton", name="Berat Badan (KG) (*)").click()
    page.get_by_role("spinbutton", name="Berat Badan (KG) (*)").fill("50")
    page.get_by_role("spinbutton", name="Tinggi Badan (CM)").click()
    page.get_by_role("spinbutton", name="LILA (CM)").click()
    page.get_by_role("spinbutton", name="LILA (CM)").fill("25")
    page.get_by_role("tabpanel", name="Step").locator("a").click()
    page.get_by_role("listitem").filter(has_text="Normal").click()
    page.get_by_role("textbox", name="Nadi (x/menit)").click()
    page.get_by_role("textbox", name="Nadi (x/menit)").fill("70")
    page.get_by_role("textbox", name="Respiratory Rate (x/menit)").click()
    page.get_by_role("textbox", name="Respiratory Rate (x/menit)").fill("80")
    page.get_by_role("spinbutton", name="Suhu Badan (Celcius)").click()
    page.get_by_role("textbox", name="Respiratory Rate (x/menit)").click()
    page.get_by_role("textbox", name="Respiratory Rate (x/menit)").fill("100")
    page.get_by_role("spinbutton", name="Suhu Badan (Celcius)").click()
    page.get_by_role("textbox", name="Respiratory Rate (x/menit)").click()
    page.get_by_role("textbox", name="Respiratory Rate (x/menit)").fill("25")
    page.get_by_role("spinbutton", name="Suhu Badan (Celcius)").click()
    page.get_by_role("textbox", name="Respiratory Rate (x/menit)").click()
    page.get_by_role("textbox", name="Respiratory Rate (x/menit)").fill("50")
    page.get_by_role("spinbutton", name="Suhu Badan (Celcius)").click()
    page.get_by_role("spinbutton", name="Suhu Badan (Celcius)").fill("36")
    page.get_by_role("spinbutton", name="Tekanan Darah (Sis) (*)").click()
    page.get_by_role("spinbutton", name="Tekanan Darah (Sis) (*)").fill("120")
    page.get_by_role("spinbutton", name="Tekanan Darah (Di) (*)").click()
    page.get_by_role("spinbutton", name="Tekanan Darah (Di) (*)").fill("80")
    page.locator("input[name=\"komplikasi_masa_nifas\"]").nth(1).check()
    page.get_by_label("Step 2").get_by_text("Ya", exact=True).nth(1).click()
    page.get_by_role("textbox", name="Note ASI").click()
    page.get_by_role("textbox", name="Note ASI").fill("eksklusif")
    page.get_by_role("radio", name="Pemeriksaan COVID-19 Ya").check()
    page.get_by_role("radio", name="Apakah ada masalah BAB Ya").check()
    page.get_by_label("Step 2").get_by_text("Ya", exact=True).nth(4).click()
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("radio", name="Ya Jumlah Tablet Fe yang").check()
    page.locator("#jumlah_fe").click()
    page.locator("#jumlah_fe").fill("2")
    page.locator("#fe_konsumsi").click()
    page.locator("#fe_konsumsi").fill("2")
    page.get_by_role("radio", name="Pemberian VIT A Ya").check()
    page.get_by_role("textbox", name="Dosis VIT A").click()
    page.get_by_role("textbox", name="Dosis VIT A").fill("2")
    page.get_by_role("textbox", name="Catatan Pemberian VIT A").click()
    page.get_by_role("textbox", name="Catatan Pemberian VIT A").fill("catatan A")
    page.get_by_role("radio", name="Konseling Ya Konseling ASI").check()
    page.locator("#a_konseling").get_by_text("Ya").click()
    page.locator("#a_tanda_bahaya_nifas").get_by_role("radio", name="Ya").check()
    page.locator("#a_konseling_kb").get_by_role("radio", name="Ya").check()
    page.locator("#a_konseling_tanda_bahaya").get_by_role("radio", name="Tidak").check()
    page.locator("#a_konseling_lainnya").get_by_role("radio", name="Tidak").check()
    page.locator("#a_konseling_phbs").get_by_role("radio", name="Ya").check()
    page.locator("#a_konseling_tali_pusar").get_by_role("radio", name="Ya").check()
    page.locator("#a_konseling_gizi").get_by_role("radio", name="Ya").check()
    page.get_by_role("textbox", name="CD4 (kopi/ml)").click()
    page.get_by_role("textbox", name="CD4 (kopi/ml)").fill("23")
    page.locator("a").filter(has_text="Pilih Obat Malaria").click()
    page.locator("#anti_malaria_chosen").get_by_text("Artesunat").click()
    page.locator("a").filter(has_text="Pilih Obat TB").click()
    page.locator("#anti_tb_chosen").get_by_text("Pyrazinamid").click()
    page.locator("#pelaksanaan_kb_pasca").first.check()
    page.get_by_role("tabpanel", name="Step").get_by_role("list").nth(2).click()
    page.locator("#metode_kontrasepsi_chosen").get_by_text("Kondom").click()
    page.get_by_role("textbox", name="Tanggal Pelaksanaan Tindakan*").click()
    page.get_by_text("7", exact=True).click()
    page.locator("#tatalaksana_komplikasi_pendarahan").first.check()
    page.locator("#pemberian_tablet_fe").first.check()
    page.locator("#transfusi_darah").first.check()
    page.locator("#tatalaksana_komplikasi_pendarahan_lain").click()
    page.locator("#tatalaksana_komplikasi_pendarahan_lain").fill("lainlain")
    page.locator("div:nth-child(7) > div > div > .col-md-12 > label").first.click()
    page.locator("#pantau_tekanan_darah").first.check()
    page.locator("#pantau_protein_urin").first.check()
    page.locator("#pantau_kondisi_janin").first.check()
    page.locator("#tatalaksana_komplikasi_hipertensi_lain").click()
    page.locator("#tatalaksana_komplikasi_hipertensi_lain").fill("lainnya")
    page.locator("#tatalaksana_komplikasi_eklampsia").first.check()
    page.locator("#pantau_tekanan_darah_eklampsia").first.check()
    page.locator("#pantau_protein_urin_eklampsia").nth(1).check()
    page.locator("#pantau_kondisi_janin_eklampsia").first.check()
    page.locator("#pemberian_diazepam").first.check()
    page.locator("#pemberian_mgso4").nth(1).check()
    page.locator("#pemberian_antihipertensi").nth(1).check()
    page.locator("#tatalaksana_komplikasi_eklampsia_lain").click()
    page.locator("#tatalaksana_komplikasi_eklampsia_lain").fill("lain lain")
    page.get_by_role("textbox", name="Catatan Terapi Tindakan").click()
    page.get_by_role("textbox", name="Catatan Terapi Tindakan").fill("terapi")
    page.get_by_role("menuitem", name="Next").click()
    page.locator("a").filter(has_text="Pilih Faskes Rujukan").click()
    page.locator("#dirujuk_ke_chosen").get_by_text("Tidak").click()
    page.locator("a").filter(has_text="Jenis Faskes Rujukan Dituju").click()
    page.locator("#jenis_faskes_rujukan_chosen").get_by_text("RS").click()
    page.locator("#nama_faskes_rujukan").click()
    page.locator("#nama_faskes_rujukan").fill("rshs")
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("radio", name="Diberikan KIE/ Konseling Ya").check()
    page.get_by_role("tabpanel", name="Step").get_by_role("list").first.click()
    page.locator("#konseling_kie_chosen").get_by_text("Konseling Menyusui dan ASI").click()
    page.get_by_role("textbox", name="Catatan Penyuluhan (KIE)").click()
    page.get_by_role("textbox", name="Catatan Penyuluhan (KIE)").fill("5")
    page.get_by_role("radio", name="Tidak").nth(1).check()
    page.get_by_role("radio", name="Dicatat Dalam Buku KIA Ya").check()
    page.get_by_role("textbox", name="Tgl Konsul Lanjutan").click()
    page.get_by_text("1", exact=True).nth(2).click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
