import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://ekohort.kemkes.go.id/administrator/login")
    page.get_by_role("textbox", name="Pilih Provinsi").click()
    page.get_by_role("option", name="JAWA BARAT").click()
    klik = page.get_by_role("textbox", name="Pilih Kabupaten")
    kab = page.get_by_role("textbox", name="Pilih Kabupaten").click()
    print(klik)
    for i in range(10):
        print("waiting for kabupaten")
        page.wait_for_timeout(1000)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        page.wait_for_timeout(100)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        kab = page.get_by_role("option", name="KABUPATEN TASIKMALAYA")
        print(kab)
        if kab.is_visible():
            print("kabupaten visible")
            break
    page.get_by_role("option", name="KABUPATEN TASIKMALAYA").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").fill("phone_number")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("password_here")
    page.get_by_role("button", name="Secure login").click()
    page.goto("https://ekohort.kemkes.go.id/administrator/user/profile")
    page.get_by_role("link", name=" Pelayanan KIA ").click()
    page.get_by_role("link", name=" Pelayanan Ibu").click()
    page.goto("https://ekohort.kemkes.go.id/administrator/rf_m_ibuhamil")
    page.locator("button:nth-child(13)").first.click()
    page.get_by_role("spinbutton", name="ID Ibu").click()
    page.get_by_role("textbox", name="Nama Ibu").click()
    page.get_by_role("radio", name="Ya").check()
    page.get_by_role("textbox", name="Tekanan Darah (Sis) (*)").click()
    page.get_by_role("textbox", name="Tekanan Darah (Sis) (*)").fill("120")
    page.get_by_role("textbox", name="Tekanan Darah (Di) (*)").click()
    page.get_by_role("textbox", name="Tekanan Darah (Di) (*)").fill("80")
    page.get_by_role("textbox", name="Frekuensi Nadi").click()
    page.get_by_role("textbox", name="Frekuensi Nadi").fill("70")
    page.get_by_text("Suhu", exact=True).click()
    page.get_by_role("textbox", name="Frekuensi Pernapasan").click()
    page.get_by_role("textbox", name="Frekuensi Pernapasan").fill("40")
    page.get_by_role("textbox", name="Suhu").click()
    page.get_by_role("textbox", name="Suhu").fill("36")
    page.get_by_role("textbox", name="Usia Kehamilan / Gestasi (").click()
    page.get_by_role("textbox", name="Usia Kehamilan / Gestasi (").fill("39")
    page.get_by_role("textbox", name="Tinggi Fundus Uteri (*)").click()
    page.get_by_role("textbox", name="Usia Kehamilan menurut HPHT (").click()
    page.get_by_role("textbox", name="Tinggi Fundus Uteri (*)").click()
    page.get_by_role("textbox", name="Tinggi Fundus Uteri (*)").fill("20")
    page.locator("a").filter(has_text="Pilih Detak Jantung Janin").click()
    page.locator("#kondisi_detak_jantung_janin_chosen").get_by_text("Normal").click()
    page.get_by_role("textbox", name="Detak Jantung Janin (x /").click()
    page.get_by_role("textbox", name="Detak Jantung Janin (x /").fill("110")
    page.get_by_role("textbox", name="Letak Janin").click()
    page.get_by_role("textbox", name="Letak Janin").fill("normal")
    page.locator("#presentasi_chosen a").click()
    page.locator("#presentasi_chosen").get_by_text("Normal").click()
    page.locator("a").filter(has_text="Pilih Posisi Kepala Thdp.").click()
    page.locator("#posisi_kepala_chosen").get_by_text("Masuk PAP", exact=True).click()
    page.locator("a").filter(has_text="Pilih Kondisi Ketuban").click()
    page.locator("#kondisi_ketuban_chosen").get_by_text("Intact", exact=True).click()
    page.get_by_role("textbox", name="Pembukaan (CM) Sebelum Ketuban").click()
    page.get_by_role("textbox", name="Pembukaan (CM) Sebelum Ketuban").fill("10")
    page.locator("#keadaan_bayi_chosen a").click()
    page.get_by_role("listitem").filter(has_text="Hidup").click()
    page.locator("#keadaan_ibu_chosen a").click()
    page.locator("#keadaan_ibu_chosen").get_by_role("list").get_by_text("Hidup").click()
    page.locator("a").filter(has_text="Pilih Tempat Melahirkan").click()
    page.locator("#tempat_persalinan_chosen").get_by_text("Poskesdes").click()
    page.locator("a").filter(has_text="PUSKESMAS TINEWATI").click()
    page.get_by_role("listitem").filter(has_text="PUSKESMAS TINEWATI").click()
    page.locator("a").filter(has_text="Pilih Penolong Persalinan").click()
    page.locator("#penolong_persalinan_chosen").get_by_text("Bidan").click()
    page.locator("a").filter(has_text="Pilih Nama Nakes").click()
    page.locator("a").filter(has_text="Pilih Nama Nakes").click()
    page.get_by_role("textbox", name="Tanggal Persalinan").click()
    page.get_by_role("cell", name="24").locator("div").click()
    page.get_by_role("textbox", name="Jam Persalinan").click()
    page.locator(".xdsoft_time_variant > div:nth-child(148)").first.click()
    page.locator("#riwayat_lab_anemia_chosen a").click()
    page.locator("#riwayat_lab_anemia_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("a").filter(has_text="Pilih Protein Urin").click()
    page.locator("#riwayat_lab_protein_urin_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("#riwayat_lab_diabetes_chosen a").click()
    page.locator("#riwayat_lab_diabetes_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("#riwayat_lab_hiv_chosen a").click()
    page.locator("#riwayat_lab_hiv_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("#riwayat_lab_hepatitis_b_chosen a").click()
    page.locator("#riwayat_lab_hepatitis_b_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("#riwayat_lab_sifilis_chosen a").click()
    page.locator("#riwayat_lab_sifilis_chosen").get_by_text("Ya").click()
    page.locator("a").filter(has_text=re.compile(r"^Pilih malaria$")).click()
    page.locator("#riwayat_lab_malaria_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("a").filter(has_text="Pilih Anemia").click()
    page.locator("#faktor_resiko_anemia_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("a").filter(has_text="Pilih Pre Eklampsia").click()
    page.locator("#faktor_resiko_pre_eklampsia_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("a").filter(has_text="Pilih Diabetes").click()
    page.locator("#faktor_resiko_diabetes_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("a").filter(has_text="Pilih HIV").click()
    page.locator("#faktor_resiko_hiv_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("a").filter(has_text="Pilih Hepatitis B").click()
    page.locator("#faktor_resiko_hepatitis_b_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("a").filter(has_text="Pilih Sifilis").click()
    page.locator("#faktor_resiko_sifilis_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("a").filter(has_text="Pilih Malaria").click()
    page.locator("#faktor_resiko_malaria_chosen").get_by_text("Tidak", exact=True).click()
    page.locator("a").filter(has_text="Pilih TB").click()
    page.locator("#faktor_resiko_tb_chosen").get_by_text("Tidak", exact=True).click()
    page.get_by_role("textbox", name="Lainnya").click()
    page.get_by_role("textbox", name="Lainnya").fill("lain lain")
    page.get_by_role("menuitem", name="Next").click()
    page.locator("a").filter(has_text="Pilih Presentasi").click()
    page.locator("#presentasi_persalinan_chosen").get_by_text("Puncak Kepala (PK)").click()
    page.locator("a").filter(has_text="Pilih Cara Persalinan").click()
    page.locator("#cara_persalinan_chosen").get_by_text("Normal").click()
    page.locator("#kala div").filter(has_text="Tanggal Kala").nth(3).click()
    page.get_by_role("textbox", name="Tanggal Kala 1").click()
    page.get_by_role("cell", name="21").click()
    page.get_by_role("textbox", name="Jam Kala 1").click()
    page.locator("div:nth-child(187) > .xdsoft_timepicker > .xdsoft_time_box > .xdsoft_time_variant > div:nth-child(146)").click()
    page.get_by_role("textbox", name="Tanggal Kala 2").click()
    page.get_by_role("cell", name="21").locator("div").click()
    page.get_by_role("textbox", name="Jam Kala 2").click()
    page.locator("div:nth-child(188) > .xdsoft_timepicker > .xdsoft_time_box > .xdsoft_time_variant > div:nth-child(147)").click()
    page.get_by_role("textbox", name="Tanggal Bayi Lahir").click()
    page.get_by_role("cell", name="22").locator("div").click()
    page.get_by_role("textbox", name="Jam Bayi Lahir").click()
    page.locator("div:nth-child(189) > .xdsoft_timepicker > .xdsoft_time_box > .xdsoft_time_variant > div:nth-child(147)").click()
    page.get_by_role("textbox", name="Tanggal Plasenta Lahir").click()
    page.locator("div:nth-child(185) > .xdsoft_datepicker > .xdsoft_monthpicker > .xdsoft_prev").click()
    page.get_by_role("cell", name="20").locator("div").click()
    page.get_by_role("textbox", name="Jam Plasenta Lahir").click()
    page.locator("a").filter(has_text="Select an Option").click()
    page.locator("#kondisi_plasenta_chosen").get_by_text("Lengkap", exact=True).click()
    page.get_by_role("list").filter(has_text=re.compile(r"^$")).first.click()
    page.locator("#kala_3_chosen").get_by_text("Masase Fundus Uteri").click()
    page.locator("a").filter(has_text="Pilih IMD").click()
    page.locator("#pelayanan_imd_chosen").get_by_text("< 1 jam").click()
    page.get_by_role("textbox", name="Kondisi Kala").click()
    page.get_by_role("textbox", name="Kondisi Kala").fill("kondisi")
    page.get_by_role("textbox", name="Jumlah Pendarahan (cc)").click()
    page.get_by_role("textbox", name="Jumlah Pendarahan (cc)").fill("1")
    page.get_by_role("textbox", name="Tekanan Darah di Kala").click()
    page.get_by_role("textbox", name="Tekanan Darah di Kala").fill("120")
    page.get_by_role("textbox", name="Tindakan di Kala").click()
    page.get_by_role("textbox", name="Tindakan di Kala").fill("kala 4")
    page.get_by_role("textbox", name="Keterangan Lainnya").click()
    page.get_by_role("textbox", name="Keterangan Lainnya").fill("ketereangan lain")
    page.get_by_role("list").filter(has_text=re.compile(r"^$")).first.click()
    page.locator("#komplikasi_chosen").get_by_text("HDK").click()
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("textbox", name="NIK Bayi").click()
    page.get_by_role("textbox", name="Nama Bayi (*)").click()
    page.get_by_role("textbox", name="Nama Bayi (*)").fill("adrian")
    page.locator("a").filter(has_text="Pilih Jenis Kelamin").click()
    page.locator("#jenkel_chosen").get_by_text("Laki-laki").click()
    page.locator("a").filter(has_text="Pilih Gol Darah").click()
    page.locator("#gol_darah_chosen").get_by_text("A", exact=True).click()
    page.get_by_role("textbox", name="Berat Saat Lahir (GR) (*)").click()
    page.get_by_role("textbox", name="Berat Saat Lahir (GR) (*)").fill("2.5")
    page.get_by_role("textbox", name="Panjang Saat Lahir (CM) (*)").click()
    page.get_by_role("textbox", name="Panjang Saat Lahir (CM) (*)").fill("14")
    page.get_by_role("radio", name="Tidak").check()
    page.get_by_role("radio", name="Punya Buku KIA Ya").check()
    page.get_by_role("textbox", name="Keterangan Kondisi Lahir").click()
    page.get_by_role("textbox", name="Keterangan Kondisi Lahir").fill("sehat")
    page.get_by_role("menuitem", name="Next").click()
    page.locator("#komplikasi_persalinan_y").check()
    page.locator("#komplikasi_persalinan_chosen").get_by_role("textbox").click()
    page.locator("#komplikasi_persalinan_chosen").get_by_text("Hipertensi").click()
    page.locator("textarea[name=\"tata_laksana_komplikasi_persalinan\"]").click()
    page.locator("textarea[name=\"tata_laksana_komplikasi_persalinan\"]").fill("tatalaksana hipertensi")
    page.locator("#rujuk1").check()
    page.locator("#faskes_rujukan").select_option("RS")
    page.locator("input[name=\"nama_faskes_rujuk\"]").click()
    page.locator("input[name=\"nama_faskes_rujuk\"]").fill("rshs")
    page.locator("#konseling_y").check()
    page.locator("#konseling").select_option("Konseling Gizi")
    page.get_by_role("tabpanel", name="Step").get_by_role("list").nth(2).click()
    page.locator("#pelayanan_chosen").get_by_text("Catat di Buku KIA").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
