import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://ekohort.kemkes.go.id/administrator/login")
    page.get_by_role("textbox", name="Pilih Provinsi").click()
    page.get_by_role("option", name="JAWA BARAT").click()
    kab = page.get_by_role("textbox", name="Pilih Kabupaten").click()
    for i in range(10):
        print("waiting for kabupaten")
        page.wait_for_timeout(1000)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        page.wait_for_timeout(100)
        page.get_by_role("textbox", name="Pilih Kabupaten").click()
        kab = page.get_by_role("option", name="KABUPATEN TASIKMALAYA")
        print(kab)
        if kab.is_visible():
            print("kabupaten visible")
            break
    page.get_by_role("option", name="KABUPATEN TASIKMALAYA").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").click()
    page.get_by_role("textbox", name="Provinsi Kabupaten/Kota").fill("phone_number")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("password_here")
    page.get_by_role("button", name="Secure login").click()
    page.get_by_role("link", name=" Pelayanan KIA ").click()
    page.get_by_role("link", name=" Pelayanan Ibu").click()
    page.get_by_role("link", name=" Tambah Data Ibu Baru").click()
    page.get_by_role("textbox", name="No Rekam Medis apabila ada").click()
    page.get_by_role("textbox", name="digit nomor kartu keluarga").click()
    page.get_by_role("textbox", name="Search").click()
    page.get_by_role("textbox", name="Nama Ibu (*)").click()
    page.get_by_role("textbox", name="Nama Ibu (*)").fill("marsita")
    page.get_by_role("textbox", name="No HP", exact=True).click()
    page.get_by_role("textbox", name="No HP", exact=True).fill("0856780090071")
    page.get_by_role("textbox", name="No WA").click()
    page.locator("a").filter(has_text="Pilih Tempat Lahir").click()
    page.locator("#id_tempat_lahir_chosen").get_by_role("textbox").fill("tas")
    page.locator("#id_tempat_lahir_chosen").get_by_text("KOTA TASIKMALAYA").click()
    page.get_by_role("textbox", name="Tgl Lahir (*)").fill("1999-06-01")
    page.get_by_role("spinbutton", name="Umur (Tahun)").click()
    page.locator("a").filter(has_text="JAWA BARAT").click()
    page.locator("a").filter(has_text="JAWA BARAT").click()
    page.locator("a").filter(has_text="KABUPATEN TASIKMALAYA").click()
    page.locator("a").filter(has_text="KABUPATEN TASIKMALAYA").click()
    page.locator("a").filter(has_text="SINGAPARNA").click()
    page.locator("#id_kecamatan2_chosen").get_by_text("SODONGHILIR").click()
    page.locator("a").filter(has_text="SUKAASIH").click()
    page.locator("#id_desa2_chosen").get_by_text("CIKUNTEN").click()
    page.get_by_role("textbox", name="RW").click()
    page.get_by_role("textbox", name="RW").fill("002")
    page.get_by_role("textbox", name="RT", exact=True).click()
    page.get_by_role("textbox", name="RT", exact=True).fill("003")
    page.get_by_role("textbox", name="Alamat").click()
    page.get_by_role("textbox", name="Alamat").fill("jln. ciereng no 12 ")
    page.locator("a").filter(has_text="Pilih Jenis Asuransi").click()
    page.locator("#jenis_asuransi_chosen").get_by_text("BPJS").click()
    page.get_by_role("textbox", name="Nomor Asuransi").click()
    page.get_by_role("textbox", name="Nomor Asuransi").fill("900800")
    page.locator("a").filter(has_text="Pilih Status Kesejahteraan").click()
    page.locator("#status_kesejahteraan_chosen").get_by_text("Keluarga Sejahtera II", exact=True).click()
    page.get_by_role("radio", name="Tidak").first.check()
    page.get_by_role("radio", name="Mempunyai Perilaku Cuci").check()
    page.get_by_role("radio", name="Tidak").nth(1).check()
    page.get_by_role("radio", name="Penanganan Tinja Dengan Baik").check()
    page.get_by_role("radio", name="Tidak").nth(2).check()
    page.get_by_role("radio", name="Akses Sumber Air Bersih? Ya").check()
    page.locator("a").filter(has_text="Pilih Pendidikan").click()
    page.locator("#pendidikan_chosen").get_by_text("Diploma IV/Strata I").click()
    page.locator("a").filter(has_text="Pilih Agama").click()
    page.locator("#agama_chosen").get_by_text("Islam").click()
    page.locator("a").filter(has_text="Pilih Pekerjaan").click()
    page.locator("#pekerjaan_chosen").get_by_role("textbox").fill("dok")
    page.locator("#pekerjaan_chosen").get_by_text("DOKTER").click()
    page.get_by_role("textbox", name="No KTP Suami / Pendamping").click()
    page.get_by_role("textbox", name="No KTP Suami / Pendamping").fill("3278081709990002")
    page.get_by_role("textbox", name="Nama Suami / Pendamping").click()
    page.get_by_role("textbox", name="Nama Suami / Pendamping").fill("brandon")
    page.get_by_role("textbox", name="No HP/WA Suami / Pendamping").click()
    page.get_by_role("textbox", name="No HP/WA Suami / Pendamping").fill("085700980010")
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("textbox", name="Hari Pertama Haid Terakhir (").fill("2025-04-01")
    page.locator("a").filter(has_text="Pilih Gol Darah").click()
    page.locator("#gol_darah_chosen").get_by_text("A", exact=True).click()
    page.locator("a").filter(has_text="Pilih Rhesus").click()
    page.locator("#rhesus_chosen").get_by_text("+").click()
    page.get_by_role("radio", name="Tidak").check()
    page.locator("#riwayat_komplikasi_chosen").get_by_role("list").first.click()
    page.locator("#riwayat_komplikasi_chosen").get_by_text("Pre Eklampsia").click()
    page.get_by_role("list").filter(has_text="Pre Eklampsia").first.click()
    page.locator("#riwayat_komplikasi_chosen").get_by_text("DM").click()
    page.locator("#riwayat_penyakit_chosen").get_by_role("list").first.click()
    page.locator("#riwayat_penyakit_chosen").get_by_text("Alergi").click()
    page.get_by_role("list").filter(has_text="Alergi").first.click()
    page.locator("#riwayat_penyakit_chosen").get_by_text("Hipertensi").click()
    page.locator("#riwayat_penyakit_keluarga_chosen").get_by_role("list").first.click()
    page.locator("#riwayat_penyakit_keluarga_chosen").get_by_text("Diabetes").click()
    page.get_by_role("list").filter(has_text=re.compile(r"^$")).first.click()
    page.locator("#riwayat_perilaku_beresiko_chosen").get_by_text("Pola Makan Beresiko").click()
    page.get_by_role("list").filter(has_text=re.compile(r"^$")).first.click()
    page.locator("#riwayat_kb_chosen").get_by_text("Suntik").click()
    page.get_by_role("menuitem", name="Next").click()
    page.get_by_role("spinbutton", name="BB Sebelum Hamil (KG)").click()
    page.get_by_role("spinbutton", name="BB Sebelum Hamil (KG)").fill("45")
    page.get_by_role("spinbutton", name="TB (CM)").click()
    page.get_by_role("spinbutton", name="TB (CM)").fill("155")
    page.locator("a").filter(has_text="Normal").click()
    page.get_by_role("listitem").filter(has_text="Normal").click()
    page.get_by_role("spinbutton", name="(G) Kehamilan Ke").click()
    page.get_by_role("spinbutton", name="(G) Kehamilan Ke").fill("1")
    page.get_by_role("textbox", name="(P) Jml Persalinan").click()
    page.get_by_role("textbox", name="(P) Jml Persalinan").fill("0")
    page.get_by_role("textbox", name="(A) Jml Keguguran").click()
    page.get_by_role("textbox", name="(P) Jml Persalinan").click()
    page.locator("a").filter(has_text="Pilih Status TT Terakhir").click()
    page.locator("#status_tt_chosen").get_by_text("TT Ke 2").click()
    page.locator("a").filter(has_text="Tempat Rencana Persalinan").click()
    page.locator("#rencana_persalinan_chosen").get_by_text("KLINIK NABILA").click()
    page.locator("a").filter(has_text="Pilih Pendamping Persalinan").click()
    page.locator("#pendamping_persalinan_chosen").get_by_text("Tetangga").click()
    page.locator("a").filter(has_text="Pilih Jenis Kendaraan").click()
    page.locator("#tr_jenis_kendaraan_chosen").get_by_text("SEPEDA MOTOR").click()
    page.get_by_role("textbox", name="Nama Pemilik/Pengemudi").click()
    page.get_by_role("textbox", name="Nama Pemilik/Pengemudi").fill("tatar")
    page.get_by_role("textbox", name="No HP/WA Pemilik/Pengemudi").click()
    page.get_by_role("textbox", name="No HP/WA Pemilik/Pengemudi").fill("087891098092")
    page.get_by_role("textbox", name="Nama Pendonor").click()
    page.get_by_role("textbox", name="Nama Pendonor").fill("ibu marsina")
    page.locator("a").filter(has_text="Pilih Golongan Darah").click()
    page.locator("#pendonor_goldar0_chosen").get_by_text("A", exact=True).click()
    page.get_by_role("textbox", name="No. HP Pendonor").click()
    page.get_by_role("textbox", name="No. HP Pendonor").fill("085400900800")
    page.get_by_role("menuitem", name="Next").click()
    page.locator("#rf_m_ibuhamil_photo_galery").get_by_text("Select Processing dropped").click()
    page.locator("#rf_m_ibuhamil_photo_ic_galery").get_by_text("Select Processing dropped").click()
    page.get_by_role("radio", name="Tidak").first.check()
    page.get_by_role("radio", name="Memiliki Buku Kia Ya").check()
    page.get_by_role("radio", name="Ikut Senam Hamil Ya").check()
    page.get_by_role("radio", name="Tidak").nth(2).check()
    page.locator("a").filter(has_text="PUSKESMAS TINEWATI").click()
    page.get_by_role("tabpanel", name="Step").get_by_role("listitem").click()
    page.locator("a").filter(has_text=re.compile(r"^ELLA NURLAELLA$")).click()
    page.locator("a").filter(has_text="Pilih Posyandu").click()
    page.locator("#id_posyandu_chosen").get_by_text("CIHAUR").click()
    page.get_by_role("tabpanel", name="Step").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
