import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://sigizikesga.kemkes.go.id/login_sisfo/")
    page.get_by_role("textbox", name="").fill("name_here")
    page.get_by_role("textbox", name="").press("Tab")
    page.get_by_role("textbox", name="Tampilkan Password ").fill("pass_here")
    page.get_by_role("textbox", name="Tampilkan Password ").press("Tab")
    page.get_by_role("checkbox").press("Tab")
    page.get_by_role("textbox", name="Masukan kata yang terlihat").fill("adopsi")
    page.get_by_role("button", name=" Login").click()
    page.get_by_role("link", name="Pelayanan Kesehatan").click()
    page.get_by_role("link", name=" ENTRY ").click()
    page.get_by_role("link", name=" Rematri ").click()
    page.get_by_role("link", name="Tambah Rematri").click()
    page.get_by_role("textbox", name="NIK/NISN").click()
    page.get_by_role("textbox", name="NIK/NISN").fill("3490091709250005")
    page.get_by_role("textbox", name="Nama").click()
    page.get_by_role("textbox", name="Nama").fill("Rahadian alfabet")
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("rahadianalfa@gmail.com")
    page.get_by_role("textbox", name="Nomor Telepon/HP Orangtua").click()
    page.get_by_role("textbox", name="Nomor Telepon/HP Orangtua").fill("089716789001")
    page.get_by_role("textbox", name="Tempat Lahir*").click()
    page.get_by_role("textbox", name="Tempat Lahir*").fill("singaparna")
    page.locator("#TL").click()
    page.get_by_role("cell", name="«").click()
    page.get_by_role("cell", name="April").click()
    page.get_by_role("cell", name="2025").click()
    page.get_by_role("cell", name="«").click()
    page.get_by_role("table").get_by_text("2015").click()
    page.get_by_text("Jul").click()
    page.get_by_role("cell", name="25").click()
    page.locator("#select2-domisiliprov-container").click()
    page.get_by_role("treeitem", name="JAWA BARAT").click()
    page.locator("#select2-domisilikab-container").click()
    page.get_by_role("treeitem", name="KAB TASIKMALAYA").click()
    page.locator("#select2-domisilikec-container").click()
    page.get_by_role("treeitem", name="SINGAPARNA").click()
    page.locator("#select2-domisilipkm-container").click()
    page.get_by_role("treeitem", name="TINEWATI").click()
    page.locator("#select2-domisilikel-container").click()
    page.get_by_role("treeitem", name="SUKAASIH").click()
    page.get_by_role("textbox", name="Alamat Lengkap").click()
    page.get_by_role("textbox", name="Alamat Lengkap").fill("jl. sukaasih no 12")
    page.get_by_role("textbox", name="RT").click()
    page.get_by_role("textbox", name="RT").fill("002")
    page.get_by_role("textbox", name="RW").click()
    page.get_by_role("textbox", name="RW").fill("001")
    page.locator("#select2-provsekolah-4b-container").click()
    page.get_by_role("treeitem", name="JAWA BARAT").click()
    page.get_by_title("KAB KAB TASIKMALAYA").click()
    page.get_by_role("treeitem", name="KAB KAB TASIKMALAYA").click()
    page.locator("#select2-kecsekolah-1d-container").click()
    page.get_by_role("treeitem", name="SINGAPARNA").click()
    page.locator("#select2-pkmsekolah-3v-container").click()
    page.get_by_role("treeitem", name="TINEWATI").click()
    page.get_by_title("-- Silahkan Pilih --").click()
    page.get_by_role("treeitem", name="SMPN 2 SINGAPARNA").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
